In [ ]:
# %xmode

Exception reporting mode: Context

In [2]:
import os
import pandas as pd
from rdflib import Graph, RDF, RDFS, OWL, BNode, URIRef
from rdflib.collection import Collection

from collections import defaultdict, Counter, deque
from statistics import median

## OWL Konzepte Vergleich

Zählt für alle 50 BioPortal Ontologien wie oft ein Konzept auftritt und bestimmt unteranderem den Durchschnitt und Median prop Konstrukt

In [ ]:
# Alle Konstrukte
# 🔧 Pfade
ONT_DIR = r"C:\Users\ilove\OneDrive\Uni\Master - Philipps Uni\Master Thesis\Ontologien\Zum Testen von Verteilungen von Konzepten\Bio Portal"
OUT_CSV = "Bio_Portal_ontology_construct_counts_full3.csv"
OUT_SUMMARY = "Bio_Portal_ontology_construct_counts_summary3.csv"
# ONT_DIR = r"C:\Users\ilove\OneDrive\Uni\Master - Philipps Uni\Master Thesis\geo_all"
# OUT_CSV = "geo_all_construct_counts_full2.csv"

# --- 1) Definition aller zu zählenden Konstrukte ---

# a) Dinge, die über rdf:type gezählt werden (Klassen/Konstrukte + Property-Eigenschaften!)
#    Manche OWL2-Varianten haben alternative Klassennamen (z. B. SymmetricObjectProperty).
TYPE_MULTI = {
    # Klassen-Axiome (TBox)
    "owl:Class": [OWL.Class],
    "rdfs:Class":[RDFS.Class],
    "owl:AllDisjointClasses": [OWL.AllDisjointClasses],
    "owl:DeprecatedClass": [OWL.DeprecatedClass],
    "owl:Ontology": [OWL.Ontology],

    # Individuen-Axiome (ABox)
    "owl:AllDifferent": [OWL.AllDifferent],
    "owl:NegativePropertyAssertion": [OWL.NegativePropertyAssertion],

    # Datatype Handling
    "rdfs:Datatype": [RDFS.Datatype],

    # RDFS Konstrukte (als Typ)
    "rdf:List": [RDF.List],

    # Property-Typen (separat reporten; NICHT in SUMME einbeziehen)
    "owl:ObjectProperty": [OWL.ObjectProperty],
    "owl:DatatypeProperty": [OWL.DatatypeProperty],
    "owl:AnnotationProperty": [OWL.AnnotationProperty],
    "owl:DeprecatedProperty": [OWL.DeprecatedProperty],
    "rdf:Property": [RDF.Property],

    "owl:AllDisjointProperties": [OWL.AllDisjointProperties],

    "owl:FunctionalProperty": [OWL.FunctionalProperty],
    "owl:InverseFunctionalProperty": [OWL.InverseFunctionalProperty],
    "owl:SymmetricProperty": [OWL.SymmetricProperty],
    "owl:AsymmetricProperty": [OWL.AsymmetricProperty],
    "owl:TransitiveProperty": [OWL.TransitiveProperty],
    "owl:ReflexiveProperty": [OWL.ReflexiveProperty],
    "owl:IrreflexiveProperty": [OWL.IrreflexiveProperty],
    
    
}

# b) Dinge, die als Prädikat auftreten (Triple-Mittelteil)
PREDICATES = {
    # Klassen-Axiome (TBox)
    "rdfs:subClassOf": RDFS.subClassOf,
    "owl:equivalentClass": OWL.equivalentClass,
    "owl:disjointWith": OWL.disjointWith,
    "owl:disjointUnionOf": OWL.disjointUnionOf,
    "owl:hasKey": OWL.hasKey,

    # Klassen-Konstruktoren
    "owl:intersectionOf": OWL.intersectionOf,
    "owl:unionOf": OWL.unionOf,
    "owl:complementOf": OWL.complementOf,
    "owl:oneOf": OWL.oneOf,  # EnumeratedClass

    # Property Restrictions
    "owl:someValuesFrom": OWL.someValuesFrom,
    "owl:allValuesFrom": OWL.allValuesFrom,
    "owl:hasValue": OWL.hasValue,
    "owl:minCardinality": OWL.minCardinality,
    "owl:maxCardinality": OWL.maxCardinality,
    "owl:cardinality": OWL.cardinality,
    "owl:minQualifiedCardinality": OWL.minQualifiedCardinality,
    "owl:maxQualifiedCardinality": OWL.maxQualifiedCardinality,
    "owl:qualifiedCardinality": OWL.qualifiedCardinality,
    "owl:hasSelf": OWL.hasSelf,
    "owl:deprecated": OWL.deprecated,

    # Property-Axiome (Prädikate)
    "rdfs:subPropertyOf": RDFS.subPropertyOf,
    "rdfs:domain": RDFS.domain,
    "rdfs:range": RDFS.range,
    "owl:propertyDisjointWith": OWL.propertyDisjointWith,
    "owl:inverseOf": OWL.inverseOf,
    "owl:equivalentProperty": OWL.equivalentProperty,
    "owl:propertyChainAxiom": OWL.propertyChainAxiom,

    # ABox
    "owl:differentFrom": OWL.differentFrom,
    "owl:sameAs": OWL.sameAs,

    # Datatype Handling (Prädikate)
    "owl:onDatatype": OWL.onDatatype,
    "owl:withRestrictions": OWL.withRestrictions,

    # RDFS (Prädikate)
    "rdf:type": RDF.type,
    "rdfs:member": RDFS.member,
    "rdfs:label": RDFS.label,
    "rdfs:comment": RDFS.comment,
    "rdfs:seeAlso": RDFS.seeAlso,
    "rdfs:isDefinedBy": RDFS.isDefinedBy,

    "owl:members": OWL.members,
    # RDF List Prädikate
    "rdf:first": RDF.first,
    "rdf:rest": RDF.rest,
}
# rdf:nil ist eine Ressource – wir zählen Vorkommen als Objekt separat
COUNT_RDF_NIL = True

# Welche Spalten NICHT in die SUMME eingehen (nur reporten)
EXCLUDE_FROM_SUM = {
    "owl:ObjectProperty",
    "owl:DatatypeProperty",
    "owl:AnnotationProperty",
    "rdf:Property",
    "owl:Class",
    "rdfs:Class"
}

EXTS = (".owl", ".ttl", ".rdf")

def count_in_graph(g):
    counts = {}

    # rdf:type-basierte Zählungen (inkl. Property-Eigenschaften als Typ!)
    for label, class_list in TYPE_MULTI.items():
        total = 0
        for cls in class_list:
            total += sum(1 for _ in g.subjects(RDF.type, cls) if isinstance(_, (URIRef)))
        counts[label] = total

    # Prädikat-basierte Zählungen
    for label, pred in PREDICATES.items():
        counts[label] = sum(1 for _ in g.triples((None, pred, None)))

    # rdf:nil (als Objekt)
    if COUNT_RDF_NIL:
        counts["rdf:nil (as object)"] = sum(1 for _ in g.triples((None, None, RDF.nil)))

    # SUMME (ohne die reinen Property-Typen)
    sum_keys = [k for k in counts.keys() if k not in EXCLUDE_FROM_SUM]
    counts["SUMME"] = sum(counts[k] for k in sum_keys if k != "SUMME")

    return counts

# --- 2) Dateien zählen & CSV mit allen Rohzahlen schreiben ---
rows = []
idx = 1
for fname in sorted(os.listdir(ONT_DIR)):
    print(f"{idx}. {fname}")
    if not fname.lower().endswith(EXTS):
        idx += 1
        continue

    path = os.path.join(ONT_DIR, fname)
    try:
        g = Graph()
        g.parse(path)
        c = count_in_graph(g)
    except Exception as e:
        # bei Fehlern alle Keys auf 0
        zero_keys = (
            list(TYPE_MULTI.keys())
            + list(PREDICATES.keys())
            + (["rdf:nil (as object)"] if COUNT_RDF_NIL else [])
            + ["SUMME"]
        )
        c = {k: 0 for k in zero_keys}
        c["_error"] = str(e)

    row = {"file": fname, **c}
    print(f"    {row}")
    rows.append(row)
    idx += 1

# Spaltenreihenfolge
columns = (
    ["file"]
    + list(TYPE_MULTI.keys())
    + list(PREDICATES.keys())
    + (["rdf:nil (as object)"] if COUNT_RDF_NIL else [])
    + ["SUMME"]
)
if any("_error" in r for r in rows):
    columns += ["_error"]

df = pd.DataFrame(rows, columns=columns)
df.to_csv(OUT_CSV, index=False)
print(f"✅ Rohzahlen gespeichert: {OUT_CSV}")

# --- 3) Auswertungstabelle (Summe, #Ontologien, %Ontologien, Ø, Median, Max) ---

# __TOTAL__ Zeilen gibt's hier nicht; wir nehmen direkt df
df = pd.read_csv(OUT_CSV)
N = len(df)

# Alle Konstruktspalten für die Auswertung:
# (Alles außer Datei-Name, _error und SUMME; Property-Typen bleiben drin – werden aber nicht zusammengezählt,
#  hier machen wir eine per-Konstrukt-Auswertung, also dürfen sie erscheinen.)
construct_cols = [c for c in df.columns if c not in ("file", "_error", "SUMME")]

summary_rows = []
for col in construct_cols:
    vals = pd.to_numeric(df[col], errors="coerce").fillna(0).astype(int)
    total = int(vals.sum())
    ont_count = int((vals > 0).sum())
    percent = (ont_count / N * 100) if N else 0

    nonzero_vals = sorted(vals[vals > 0].tolist())
    if ont_count > 0:
        avg = float(vals[vals > 0].mean())
        med = float(vals[vals > 0].median())
        minv = min(nonzero_vals)
        avg_0 = float(vals[vals >= 0].mean())
        med_0 = float(vals[vals >= 0].median())
    else:
        avg = med = minv = avg_0 = med_0 = 0.0
        
    maxv = int(vals.max()) if len(vals) else 0

    summary_rows.append({
        "Construct": col,
        "Summe": total,
        "#Ontologien": ont_count,
        "%Ontologien": round(percent, 1),
        "Ø pro Ontologie (ohne 0)": round(avg, 2),
        "Ø pro Ontologie (mit 0)": round(avg_0, 2),
        "Median (ohne 0)": med,
        "Median (mit 0)": med_0,
        "Min (>0)": minv,
        "Max": maxv,
        "Werte (für Median ohne 0)": nonzero_vals,  # hier alle Werte explizit
        "Werte (für Median mit 0)": sorted(vals.tolist())
    })

summary_df = pd.DataFrame(summary_rows).sort_values(by=["Summe", "#Ontologien"], ascending=False)
summary_df.to_csv(OUT_SUMMARY, index=False)

print(f"✅ Auswertung gespeichert: {OUT_SUMMARY}")
summary_df

1. Allergidoc.rdf
    {'file': 'Allergidoc.rdf', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 0, 'SUMME': 0}
2. BMONT.owl
    {'file': 'BMONT.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 0, 'SUMME': 0}
3. CDMOnto.owl
    {'file': 'CDMOnto.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 0, 'SUMME': 0}
4. COPPER.owl
    {'file': 'COPPER.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 1, 'SUMME': 1}
5. CTCAE_5.0.owl
    {'file': 'CTCAE_5.0.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 0, 'SUMME': 0}
6. DMDSONT.rdf
    {'file': 'DMDSONT.rdf', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 179, 'SUMME': 179}
7. EDAM.owl
    {'file': 'EDAM.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 2, 'SUMME': 2}
8. GAMUTS.owl
    {'file': 'GAMUTS.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 0, 'SUMME': 0}
9. O3_20250709.owl
    {'file': 'O3_20250709.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 0, 'SUMME': 0}
10. OBOREL.owl
    {'file': 'OBOREL.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 10, 'rdf:nil (as object)': 242, 'SUMME': 252}
11. OntoCaimerV2-Joe-Mary.owl
    {'file': 'OntoCaimerV2-Joe-Mary.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 46, 'SUMME': 46}
12. Ontos mit InverseOf
13. Ontos mit PropertyChainAxiom
14. bbo.rdf
    {'file': 'bbo.rdf', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 5, 'rdf:nil (as object)': 201, 'SUMME': 206}
15. bcio.owl
    {'file': 'bcio.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 19, 'SUMME': 19}
16. bervo.owl
    {'file': 'bervo.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 0, 'SUMME': 0}
17. cl.owl
    {'file': 'cl.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 12809, 'SUMME': 12809}
18. clo_merged.owl
    {'file': 'clo_merged.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 13513, 'SUMME': 13513}
19. cob.owl
    {'file': 'cob.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 6, 'SUMME': 6}
20. envo.owl
    {'file': 'envo.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 2444, 'SUMME': 2444}
21. evora_ontology.ttl
    {'file': 'evora_ontology.ttl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 64, 'SUMME': 64}
22. foodon.owl
    {'file': 'foodon.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 8381, 'SUMME': 8381}
23. fypo.owl
    {'file': 'fypo.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 13502, 'SUMME': 13502}
24. gbol-ontology.ttl
    {'file': 'gbol-ontology.ttl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 723, 'SUMME': 723}
25. hhear_properties.rdf
    {'file': 'hhear_properties.rdf', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 530, 'SUMME': 530}
26. hso.owl
    {'file': 'hso.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 1, 'rdf:nil (as object)': 108, 'SUMME': 109}
27. jfo_v005.ttl
    {'file': 'jfo_v005.ttl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 0, 'SUMME': 0}
28. meo.v.1.0.ttl
    {'file': 'meo.v.1.0.ttl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 24, 'SUMME': 24}
29. metpo.owl
    {'file': 'metpo.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 0, 'SUMME': 0}
30. mro.owl
    {'file': 'mro.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 28311, 'SUMME': 28311}
31. mwo.owl
    {'file': 'mwo.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 106, 'SUMME': 106}
32. namo.owl.ttl
    {'file': 'namo.owl.ttl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 24, 'SUMME': 24}
33. nando_2025-08-26.ttl
    {'file': 'nando_2025-08-26.ttl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 0, 'SUMME': 0}
34. nochmal
35. oae_merged.owl
    {'file': 'oae_merged.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 1, 'rdf:nil (as object)': 1292, 'SUMME': 1293}
36. oba.owl
    {'file': 'oba.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 92269, 'SUMME': 92269}
37. obi.owl
    {'file': 'obi.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 4818, 'SUMME': 4818}
38. odfa.owl
    {'file': 'odfa.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 20, 'SUMME': 20}
39. ordo_orphanet.owl
    {'file': 'ordo_orphanet.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 0, 'SUMME': 0}
40. part_0
41. pato.owl
    {'file': 'pato.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 4727, 'SUMME': 4727}
42. pcl.owl
    {'file': 'pcl.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 28777, 'SUMME': 28777}
43. phases.owl
    {'file': 'phases.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 21, 'SUMME': 21}
44. phipo.owl
    {'file': 'phipo.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 1566, 'SUMME': 1566}
45. plantso.owl
    {'file': 'plantso.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 385, 'SUMME': 385}
46. psdo.rdf
    {'file': 'psdo.rdf', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 489, 'SUMME': 489}
47. rbo.owl
    {'file': 'rbo.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 1, 'rdf:nil (as object)': 6110, 'SUMME': 6111}
48. sio-release.owl
    {'file': 'sio-release.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 157, 'SUMME': 157}
49. sleep.rdf
    {'file': 'sleep.rdf', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 0, 'SUMME': 0}
50. slso.owl
    {'file': 'slso.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 5, 'rdf:nil (as object)': 1348, 'SUMME': 1353}
51. ssbd_v20250512.ttl
    {'file': 'ssbd_v20250512.ttl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 52, 'SUMME': 52}
52. tara-acupoints-inferred.rdf
    {'file': 'tara-acupoints-inferred.rdf', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 380, 'SUMME': 380}
53. uberon.owl
    {'file': 'uberon.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 2, 'rdf:nil (as object)': 14155, 'SUMME': 14157}
54. with imports
55. xpo.owl
    {'file': 'xpo.owl', 'owl:AllDisjointProperties': 0, 'owl:propertyDisjointWith': 0, 'rdf:nil (as object)': 63610, 'SUMME': 63610}
✅ Rohzahlen gespeichert: Bio_Portal_ontology_construct_counts_full3.csv
✅ Auswertung gespeichert: Bio_Portal_ontology_construct_counts_summary3.csv

,Construct,Summe,#Ontologien,%Ontologien,Ø pro Ontologie (ohne 0),Ø pro Ontologie (mit 0),Median (ohne 0),Median (mit 0),Min (>0),Max,Werte (für Median ohne 0),Werte (für Median mit 0)
2,rdf:nil (as object),301411,38,76.0,7931.87,6028.22,437.0,132.5,1.0,92269,"[1, 2, 6, 19, 20, 21, 24, 24, 46, 52, 64, 106,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 6, ..."
1,owl:propertyDisjointWith,25,7,14.0,3.57,0.50,2.0,0.0,1.0,10,"[1, 1, 1, 2, 5, 5, 10]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
0,owl:AllDisjointProperties,0,0,0.0,0.00,0.00,0.0,0.0,0.0,0,[],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

Zählt für die 23 BioPortal Ontologien die PropertyChainAxiome haben, aus wie vielen Elementen diese jeweils bestehen

In [ ]:
# PropertyChainAxiom
# 🔧 Pfade
ONT_DIR = r"C:\Users\ilove\OneDrive\Uni\Master - Philipps Uni\Master Thesis\Ontologien\Zum Testen von Verteilungen von Konzepten\Bio Portal\Ontos mit PropertyChainAxiom"
OUT_CSV = "Bio_Portal_ontology_construct_depth_count_2.csv"
OUT_SUMMARY = "Bio_Portal_ontology_construct_depth_summary_2.csv"

EXTS = (".owl", ".ttl", ".rdf")

# b) Dinge, die als Prädikat auftreten (Triple-Mittelteil)
PREDICATES = {
    "owl:propertyChainAxiom": OWL.propertyChainAxiom,
}

def count_in_graph(g: Graph) -> dict:
    counts = {}

    for label, pred in PREDICATES.items():
        results = []
        for super_prop in g.subjects(OWL.propertyChainAxiom, None):
            head = g.value(super_prop, OWL.propertyChainAxiom)
            if head is None:
                continue

            length = 0
            for item in Collection(g, head):
                if isinstance(item, BNode):
                    if g.value(item, OWL.inverseOf) is not None:
                        # inverse Property Expression → zählt als 1
                        length += 1
                    elif g.value(item, OWL.propertyChainAxiom) is not None:
                        # falls verschachtelte Liste → deren Länge summieren
                        length += sum(1 for _ in Collection(g, item))
                    else:
                        # unbekannter BNode → konservativ als 1 zählen
                        length += 1
                else:
                    # normale URI einer Property
                    length += 1
            results.append(length)

        # Anzahl Ketten
        counts[label] = sum(1 for _ in g.triples((None, pred, None)))

        # Maximal-Länge
        counts["maxLength"] = max(results) if results else 0

        # Verteilung der Längen → jede Länge eigene Spalte
        length_counts = Counter(results)
        for l, cnt in length_counts.items():
            counts[f"len_{l}"] = cnt

    return counts


# --- Dateien durchgehen ---
rows = []
idx = 1
for fname in sorted(os.listdir(ONT_DIR)):
    print(f"{idx}. {fname}")
    if not fname.lower().endswith(EXTS):
        idx += 1
        continue

    path = os.path.join(ONT_DIR, fname)
    try:
        g = Graph()
        g.parse(path)
        c = count_in_graph(g)
    except Exception as e:
        zero_keys = list(PREDICATES.keys())
        c = {k: 0 for k in zero_keys}
        c["_error"] = str(e)

    row = {"file": fname, **c}
    print(f"    {row}")
    rows.append(row)
    idx += 1

# DataFrame bauen
df = pd.DataFrame(rows).fillna(0)

# CSV speichern
df.to_csv(OUT_CSV, index=False)
print(f"✅ Ergebnisse gespeichert: {OUT_CSV}")

df = pd.read_csv(OUT_CSV)
N = len(df)

construct_cols = [c for c in df.columns if c not in ("file", "total")]

summary_rows = []
for col in construct_cols:
    vals = pd.to_numeric(df[col], errors="coerce").fillna(0).astype(int)
    total = int(vals.sum())
    ont_count = int((vals > 0).sum())
    percent = (ont_count / N * 100) if N else 0

    nonzero_vals = sorted(vals[vals > 0].tolist())
    if ont_count > 0:
        avg = float(vals[vals > 0].mean())
        med = float(vals[vals > 0].median())
        minv = min(nonzero_vals)
        avg_0 = float(vals[vals >= 0].mean())
        med_0 = float(vals[vals >= 0].median())
    else:
        avg = med = minv = avg_0 = med_0 = 0.0
        
    maxv = int(vals.max()) if len(vals) else 0

    summary_rows.append({
        "Construct": col,
        "Summe": total,
        "#Ontologien": ont_count,
        "%Ontologien": round(percent, 1),
        "Ø pro Ontologie (ohne 0)": round(avg, 2),
        "Ø pro Ontologie (mit 0)": round(avg_0, 2),
        "Median (ohne 0)": med,
        "Median (mit 0)": med_0,
        "Min (> 0)": minv,
        "Max": maxv,
        "Werte (> 0)": nonzero_vals,  # hier alle Werte explizit
        # "Werte (für Median mit 0)": sorted(vals.tolist())
    })

summary_df = pd.DataFrame(summary_rows).sort_values(by=["Summe", "#Ontologien"], ascending=False)
summary_df.to_csv(OUT_SUMMARY, index=False)

print(f"✅ Auswertung gespeichert: {OUT_SUMMARY}")
print("\nZusammenfassung:\n", summary_df)

✅ Auswertung gespeichert: Bio_Portal_ontology_construct_depth_summary_2.csv

Zusammenfassung:
                 Construct  Summe  #Ontologien  %Ontologien  \
0  owl:propertyChainAxiom   1297           23        100.0
2                   len_2   1200           23        100.0
3                   len_3     82           12         52.2
1               maxLength     59           23        100.0
4                   len_4     15            1          4.3

   Ø pro Ontologie (ohne 0)  Ø pro Ontologie (mit 0)  Median (ohne 0)  \
0                     56.39                    56.39             63.0
2                     52.17                    52.17             63.0
3                      6.83                     3.57              5.0
1                      2.57                     2.57              3.0
4                     15.00                     0.65             15.0

   Median (mit 0)  Min (> 0)  Max  \
0            63.0          1  151
2            63.0          1  136
3             2.0          2   20
1             3.0          2    4
4             0.0         15   15

                                         Werte (> 0)
0  [1, 1, 2, 2, 3, 4, 15, 31, 41, 50, 60, 63, 67,...
2  [1, 1, 2, 2, 3, 4, 6, 13, 31, 45, 58, 63, 64, ...
3             [2, 2, 2, 5, 5, 5, 5, 7, 7, 7, 15, 20]
1  [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, ...
4                                               [15]

Zählt für alle 50 BioPortal Ontologien wie häufig für Proeprties die Konstrukt-Kombinationen Inverse + subProeprty, Inverse + Superproperty und Inverse + Äquivalente Property auftreten

In [ ]:

# InverseOf + Sub/SuperPropertyOf und EquivalentProperty
def count_patterns(g):
    sub_inv = super_inv = equiv_inv = func_inv =invfunc_inv = sym_inv = asym_inv = tran_inv = ref_inv = irref_inv = 0

    # --- Fall 1+2: Direkt modelliert (gleiches Subjekt) ---
    inverses = {x for s, p, o in g.triples((None, OWL.inverseOf, None)) for x in (s, o)}
    for s in inverses:
        if (s, RDFS.subPropertyOf, None) in g:
            sub_inv += 1
        if (None, RDFS.subPropertyOf, s) in g:
            super_inv += 1
        if (s, OWL.equivalentProperty, None) in g or (None, OWL.equivalentProperty, s) in g:
            equiv_inv += 1
        if (s, RDF.type, OWL.FunctionalProperty) in g:
            func_inv += 1
        if (s, RDF.type, OWL.InverseFunctionalProperty) in g:
            invfunc_inv += 1
        if (s, RDF.type, OWL.SymmetricProperty) in g:
            sym_inv += 1
        if (s, RDF.type, OWL.AsymmetricProperty) in g:
            asym_inv += 1
        if (s, RDF.type, OWL.TransitiveProperty) in g:
            tran_inv += 1
        if (s, RDF.type, OWL.ReflexiveProperty) in g:
            ref_inv += 1
        if (s, RDF.type, OWL.IrreflexiveProperty) in g:
            irref_inv += 1

    # --- Fall 3: BNode-Konstrukte ---
    for s, _, o in g.triples((None, RDFS.subPropertyOf, None)):
        if isinstance(o, BNode) and (o, OWL.inverseOf, None) in g:
            sub_inv += 1
    for s, _, o in g.triples((None, OWL.equivalentProperty, None)):
        if isinstance(o, BNode) and (o, OWL.inverseOf, None) in g:
            equiv_inv += 1

    return sub_inv, super_inv, equiv_inv, func_inv, invfunc_inv, sym_inv, asym_inv, tran_inv, ref_inv, irref_inv

# --- Lauf über alle Ontologien ---
ONT_DIR = r"C:\Users\ilove\OneDrive\Uni\Master - Philipps Uni\Master Thesis\Ontologien\Zum Testen von Verteilungen von Konzepten\Bio Portal"
OUT_CSV = "Bio_Portal_ontology_inverse_combinations_counts_full_21.csv"
OUT_SUMMARY = "Bio_Portal_ontology_inverse_combinations_counts_summary_22.csv"

# results = []
# count = 1
# for fname in os.listdir(ONT_DIR):
#     print(count, fname)
#     count += 1
#     if not fname.endswith((".ttl", ".rdf", ".owl")):
#         continue
#     path = os.path.join(ONT_DIR, fname)
#     g = Graph()
#     try:
#         g.parse(path)
#         sub_inv, super_inv, equiv_inv, func_inv, invfunc_inv, sym_inv, asym_inv, tran_inv, ref_inv, irref_inv = count_patterns(g)
#     except Exception as e:
#         sub_inv, equiv_inv = 0, 0
#     results.append({
#         "file": fname,
#         "subProperty+inverse": sub_inv,
#         "superProperty+inverse": super_inv,
#         "equivalentProperty+inverse": equiv_inv,
#         "functionalProperty+inverse": func_inv,
#         "inverseFunctionalProperty+inverse": invfunc_inv,
#         "symmetricProperty+inverse": sym_inv,
#         "asymmetricProperty+inverse": asym_inv,
#         "transitiveProperty+inverse": tran_inv,
#         "reflexiveProperty+inverse": ref_inv,
#         "irreflexiveProperty+inverse": irref_inv
#     })

# df = pd.DataFrame(results)
# df.to_csv(OUT_CSV, index=False)
# print(f"✅ Rohzahlen gespeichert: {OUT_CSV}")

# --- Statistik berechnen ---
df = pd.read_csv(OUT_CSV)
N = len(df)

construct_cols = [c for c in df.columns if c not in ("file", "total")]

summary_rows = []
for col in construct_cols:
    vals = pd.to_numeric(df[col], errors="coerce").fillna(0).astype(int)
    total = int(vals.sum())
    ont_count = int((vals > 0).sum())
    percent = (ont_count / N * 100) if N else 0

    nonzero_vals = sorted(vals[vals > 0].tolist())
    if ont_count > 0:
        avg = float(vals[vals > 0].mean())
        med = float(vals[vals > 0].median())
        minv = min(nonzero_vals)
        avg_0 = float(vals[vals >= 0].mean())
        med_0 = float(vals[vals >= 0].median())
    else:
        avg = med = minv = avg_0 = med_0 = 0.0
        
    maxv = int(vals.max()) if len(vals) else 0

    summary_rows.append({
        "Construct": col,
        "Summe": total,
        "#Ontologien": ont_count,
        "%Ontologien": round(percent, 1),
        "Ø pro Ontologie (ohne 0)": round(avg, 2),
        "Ø pro Ontologie (mit 0)": round(avg_0, 2),
        "Median (ohne 0)": med,
        "Median (mit 0)": med_0,
        "Min (> 0)": minv,
        "Max": maxv,
        "Werte (> 0)": nonzero_vals,  # hier alle Werte explizit
        # "Werte (für Median mit 0)": sorted(vals.tolist())
    })

summary_df = pd.DataFrame(summary_rows).sort_values(by=["Summe", "#Ontologien"], ascending=False)
summary_df.to_csv(OUT_SUMMARY, index=False)

print(f"✅ Auswertung gespeichert: {OUT_SUMMARY}")
print("\nZusammenfassung:\n", summary_df)

✅ Auswertung gespeichert: Bio_Portal_ontology_inverse_combinations_counts_summary_22.csv

Zusammenfassung:
                            Construct  Summe  #Ontologien  %Ontologien  \
0                subProperty+inverse   1971           25         83.3
1              superProperty+inverse    813           25         83.3
7         transitiveProperty+inverse    367           26         86.7
2         equivalentProperty+inverse    102            4         13.3
3         functionalProperty+inverse     60           23         76.7
4  inverseFunctionalProperty+inverse     37           22         73.3
9        irreflexiveProperty+inverse     33           17         56.7
6         asymmetricProperty+inverse     24           14         46.7
5          symmetricProperty+inverse     13            5         16.7
8          reflexiveProperty+inverse      4            2          6.7

   Ø pro Ontologie (ohne 0)  Ø pro Ontologie (mit 0)  Median (ohne 0)  \
0                     78.84                    65.70             64.0
1                     32.52                    27.10             29.0
7                     14.12                    12.23             14.5
2                     25.50                     3.40             21.0
3                      2.61                     2.00              1.0
4                      1.68                     1.23              1.0
9                      1.94                     1.10              2.0
6                      1.71                     0.80              1.0
5                      2.60                     0.43              1.0
8                      2.00                     0.13              2.0

   Median (mit 0)  Min (> 0)  Max  \
0            51.5          3  247
1            27.5          1   87
7            12.0          2   32
2             0.0          6   54
3             1.0          1   13
4             1.0          1    8
9             1.0          1    3
6             0.0          1    6
5             0.0          1    5
8             0.0          2    2

                                         Werte (> 0)
0  [3, 16, 17, 18, 18, 25, 25, 47, 49, 50, 53, 63...
1  [1, 7, 9, 9, 9, 9, 10, 18, 26, 27, 28, 28, 29,...
7  [2, 2, 4, 6, 6, 6, 7, 8, 8, 9, 12, 12, 12, 17,...
2                                     [6, 6, 36, 54]
3  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, ...
4  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
9  [1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, ...
6         [1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 6]
5                                    [1, 1, 1, 5, 5]
8                                             [2, 2]

Zählt für die 50 BioPortal Ontologien wie oft Kombinationen von Property-Eigenschaften auftreten.\
Es werden nur min einmal gefundene Eigenschaftskombis in die csv aufgenommen. D.h. alle nicht in der csv aufgeführten Kombis kommen in den 50 Ontologien nicht einmal vor.

In [4]:
# Property Eigenschaften Kombis
# Ordner mit Ontologien
ONT_DIR = r"C:\Users\ilove\OneDrive\Uni\Master - Philipps Uni\Master Thesis\Ontologien\Zum Testen von Verteilungen von Konzepten\Bio Portal"
OUT_CSV = "Bio_Portal_ontology_characteristic_combos_counts_full_2.csv"
OUT_SUMMARY = "Bio_Portal_ontology_characteristic_combos_counts_summary_2.csv"

EXTS = (".owl", ".ttl", ".rdf")

# Property-Eigenschaften
PROP_CHARACTERISTICS = {
    "TransitiveProperty": OWL.TransitiveProperty,
    "FunctionalProperty": OWL.FunctionalProperty,
    "SymmetricProperty": OWL.SymmetricProperty,
    "InverseFunctionalProperty": OWL.InverseFunctionalProperty,
    "IrreflexiveProperty": OWL.IrreflexiveProperty,
    "AsymmetricProperty": OWL.AsymmetricProperty,
    "ReflexiveProperty": OWL.ReflexiveProperty,
}

rows = []
idx = 1
for fname in sorted(os.listdir(ONT_DIR)):
    if not fname.lower().endswith(EXTS):
        continue

    path = os.path.join(ONT_DIR, fname)
    print(f"{idx}. {fname}")
    idx += 1

    try:
        g = Graph()
        g.parse(path)
    except Exception as e:
        print(f"   Fehler beim Parsen: {e}")
        continue

    # Zähler für diese Ontologie
    combo_counts = {}

    for prop in g.subjects(RDF.type, OWL.ObjectProperty):
        characs = []
        for name, owl_type in PROP_CHARACTERISTICS.items():
            if (prop, RDF.type, owl_type) in g:
                characs.append(name)

        if characs:
            combo = "+".join(sorted(characs))
        else:
            combo = "None"  # keine Eigenschaft

        combo_counts[combo] = combo_counts.get(combo, 0) + 1

    # Ergebniszeile für diese Ontologie
    row = {"file": fname}
    row.update(combo_counts)
    rows.append(row)

# DataFrame bauen
df = pd.DataFrame(rows).fillna(0).set_index("file")

# CSV speichern
df.to_csv(OUT_CSV)
print(f"✅ Ergebnisse gespeichert in {OUT_CSV}")

df = pd.read_csv(OUT_CSV)
N = len(df)

# Alle Konstruktspalten für die Auswertung:
# (Alles außer Datei-Name, _error und SUMME; Property-Typen bleiben drin – werden aber nicht zusammengezählt,
#  hier machen wir eine per-Konstrukt-Auswertung, also dürfen sie erscheinen.)
construct_cols = [c for c in df.columns if c not in ("file", "_error", "SUMME")]

summary_rows = []
for col in construct_cols:
    vals = pd.to_numeric(df[col], errors="coerce").fillna(0).astype(int)
    total = int(vals.sum())
    ont_count = int((vals > 0).sum())
    percent = (ont_count / N * 100) if N else 0

    nonzero_vals = sorted(vals[vals > 0].tolist())
    if ont_count > 0:
        avg = float(vals[vals > 0].mean())
        med = float(vals[vals > 0].median())
        minv = min(nonzero_vals)
        avg_0 = float(vals[vals >= 0].mean())
        med_0 = float(vals[vals >= 0].median())
    else:
        avg = med = minv = avg_0 = med_0 = 0.0
        
    maxv = int(vals.max()) if len(vals) else 0

    summary_rows.append({
        "Construct": col,
        "Summe": total,
        "#Ontologien": ont_count,
        "%Ontologien": round(percent, 1),
        "Ø pro Ontologie (ohne 0)": round(avg, 2),
        "Ø pro Ontologie (mit 0)": round(avg_0, 2),
        "Median (ohne 0)": med,
        "Median (mit 0)": med_0,
        "Min (>0)": minv,
        "Max": maxv,
        "Werte (für Median ohne 0)": nonzero_vals,  # hier alle Werte explizit
        "Werte (für Median mit 0)": sorted(vals.tolist())
    })

summary_df = pd.DataFrame(summary_rows).sort_values(by=["Summe", "#Ontologien"], ascending=False)
summary_df.to_csv(OUT_SUMMARY, index=False)

print(f"✅ Auswertung gespeichert: {OUT_SUMMARY}")
summary_df

df.head()

1. Allergidoc.rdf
2. BMONT.owl
3. CDMOnto.owl
4. COPPER.owl
5. CTCAE_5.0.owl
6. DMDSONT.rdf
7. EDAM.owl
8. GAMUTS.owl
9. O3_20250709.owl
10. OBOREL.owl
11. OntoCaimerV2-Joe-Mary.owl
12. bbo.rdf
13. bcio.owl
14. bervo.owl
15. cl.owl
16. clo_merged.owl
17. cob.owl
18. envo.owl
19. evora_ontology.ttl
20. foodon.owl
21. fypo.owl
22. gbol-ontology.ttl
23. hhear_properties.rdf
24. hso.owl
25. jfo_v005.ttl
26. meo.v.1.0.ttl
27. metpo.owl
28. mro.owl
29. mwo.owl
30. namo.owl.ttl
31. nando_2025-08-26.ttl
32. oae_merged.owl
33. oba.owl
34. obi.owl
35. odfa.owl
36. ordo_orphanet.owl
37. pato.owl
38. pcl.owl
39. phases.owl
40. phipo.owl
41. plantso.owl
42. psdo.rdf
43. rbo.owl
44. sio-release.owl
45. sleep.rdf
46. slso.owl
47. ssbd_v20250512.ttl
48. tara-acupoints-inferred.rdf
49. uberon.owl
50. xpo.owl
✅ Ergebnisse gespeichert in Bio_Portal_ontology_characteristic_combos_counts_full_2.csv
✅ Auswertung gespeichert: Bio_Portal_ontology_characteristic_combos_counts_summary_2.csv

,file,None,TransitiveProperty,AsymmetricProperty+TransitiveProperty,FunctionalProperty,InverseFunctionalProperty,SymmetricProperty+TransitiveProperty,SymmetricProperty,IrreflexiveProperty,AsymmetricProperty+IrreflexiveProperty,IrreflexiveProperty+SymmetricProperty,AsymmetricProperty,FunctionalProperty+InverseFunctionalProperty,ReflexiveProperty+TransitiveProperty,ReflexiveProperty+SymmetricProperty
0,Allergidoc.rdf,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,BMONT.owl,8.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,CDMOnto.owl,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,COPPER.owl,64.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,CTCAE_5.0.owl,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# Anzahl Domain-/Rangeklassen
# Pfade
ONT_DIR = r"C:\Users\ilove\OneDrive\Uni\Master - Philipps Uni\Master Thesis\Ontologien\Zum Testen von Verteilungen von Konzepten\Bio Portal"
OUT_DIST = "Bio_Portal_ontology_domain_range_distributions_full_2.csv"
OUT_SUMMARY = "Bio_Portal_ontology_domain_range_distributions_summary_2.csv"

EXTS = (".owl", ".ttl", ".rdf")

def get_counts(g: Graph):
    """Zählt pro Property die Anzahl an Domains und Ranges."""
    domains, ranges = [], []
    for prop_type in (OWL.ObjectProperty, OWL.DatatypeProperty):
        for prop in g.subjects(RDF.type, prop_type):
            d_count = len(set(g.objects(prop, RDFS.domain)))
            r_count = len(set(g.objects(prop, RDFS.range)))
            domains.append(d_count)
            ranges.append(r_count)
    return domains, ranges

def distribution(values):
    """Erzeugt ein Dict: Wert -> Häufigkeit."""
    dist = {}
    for v in values:
        dist[v] = dist.get(v, 0) + 1
    return dist

def summarize(values):
    """Statistiken über alle Ontologien zusammen."""
    if not values:
        return {
            "avg_with0": 0, "median_with0": 0,
            "avg_no0": 0, "median_no0": 0,
            "min_no0": 0, "max": 0,
            "distribution": {}
        }

    dist = distribution(values)

    # Mit 0en
    avg_with0 = sum(values) / len(values)
    med_with0 = median(values)
    max_val = max(values)

    # Ohne 0en
    nonzero = [v for v in values if v > 0]
    if nonzero:
        avg_no0 = sum(nonzero) / len(nonzero)
        med_no0 = median(nonzero)
        min_no0 = min(nonzero)
    else:
        avg_no0 = med_no0 = min_no0 = 0

    return {
        "avg_with0": round(avg_with0, 2),
        "median_with0": med_with0,
        "avg_no0": round(avg_no0, 2),
        "median_no0": med_no0,
        "min_no0": min_no0,
        "max": max_val,
        "distribution": dist
    }

# -------------------
# Durch alle Ontologien
# -------------------
rows = []
all_domains, all_ranges = [], []

idx = 1
for fname in sorted(os.listdir(ONT_DIR)):
    if not fname.lower().endswith(EXTS):
        continue

    path = os.path.join(ONT_DIR, fname)
    print(f"{idx}. {fname}")
    idx += 1

    try:
        g = Graph()
        g.parse(path)
    except Exception as e:
        print(f"   Fehler beim Parsen: {e}")
        continue

    domains, ranges = get_counts(g)
    all_domains.extend(domains)
    all_ranges.extend(ranges)

    dom_dist = distribution(domains)
    ran_dist = distribution(ranges)

    row = {"file": fname}
    for k, v in dom_dist.items():
        row[f"domains_val_{k}"] = v
    for k, v in ran_dist.items():
        row[f"ranges_val_{k}"] = v

    rows.append(row)

# DataFrame pro Ontologie (nur Verteilungen)
df_dist = pd.DataFrame(rows).fillna(0)
num_cols = [c for c in df_dist.columns if c != "file"]
df_dist[num_cols] = df_dist[num_cols].astype(int)
df_dist.to_csv(OUT_DIST, index=False)
print(f"✅ Verteilungen gespeichert in {OUT_DIST}")

df = pd.read_csv(OUT_DIST)
N = len(df)

construct_cols = [c for c in df.columns if c not in ("file", "total")]

summary_rows = []
for col in construct_cols:
    vals = pd.to_numeric(df[col], errors="coerce").fillna(0).astype(int)
    total = int(vals.sum())
    ont_count = int((vals > 0).sum())
    percent = (ont_count / N * 100) if N else 0

    nonzero_vals = sorted(vals[vals > 0].tolist())
    if ont_count > 0:
        avg = float(vals[vals > 0].mean())
        med = float(vals[vals > 0].median())
        minv = min(nonzero_vals)
        avg_0 = float(vals[vals >= 0].mean())
        med_0 = float(vals[vals >= 0].median())
    else:
        avg = med = minv = avg_0 = med_0 = 0.0
        
    maxv = int(vals.max()) if len(vals) else 0

    summary_rows.append({
        "Construct": col,
        "Summe": total,
        "#Ontologien": ont_count,
        "%Ontologien": round(percent, 1),
        "Ø pro Ontologie (ohne 0)": round(avg, 2),
        "Ø pro Ontologie (mit 0)": round(avg_0, 2),
        "Median (ohne 0)": med,
        "Median (mit 0)": med_0,
        "Min (> 0)": minv,
        "Max": maxv,
        "Werte (> 0)": nonzero_vals,  # hier alle Werte explizit
        # "Werte (für Median mit 0)": sorted(vals.tolist())
    })

summary_df = pd.DataFrame(summary_rows).sort_values(by=["Summe", "#Ontologien"], ascending=False)
summary_df.to_csv(OUT_SUMMARY, index=False)

print(f"✅ Auswertung gespeichert: {OUT_SUMMARY}")
print("\nZusammenfassung:\n", summary_df)

In [ ]:
# rdf:Type Kombinationen

# Ordner mit Ontologien
ONT_DIR = r"C:\Users\ilove\OneDrive\Uni\Master - Philipps Uni\Master Thesis\Ontologien\Zum Testen von Verteilungen von Konzepten\Bio Portal"
OUT_CSV = "Bio_Portal_ontology_type_combinations_counts_full_2.csv"
OUT_SUMMARY = "Bio_Portal_ontology_type_combinations_counts_summary_2.csv"

EXTS = (".owl", ".ttl", ".rdf")

def short_name(uri):
    """OWL-URI in Kurzform bringen, z.B. ...#ObjectProperty → ObjectProperty"""
    return str(uri).split("#")[-1]

# Sammeln
rows = []
combo_counts_global = {}

idx = 1
for fname in sorted(os.listdir(ONT_DIR)):
    if not fname.lower().endswith(EXTS):
        continue

    path = os.path.join(ONT_DIR, fname)
    print(f"{idx}. {fname}")
    idx += 1

    try:
        g = Graph()
        g.parse(path)
    except Exception as e:
        print(f"   Fehler beim Parsen: {e}")
        continue

    combo_counts_onto = {}

    for prop in g.subjects(RDF.type, None):
        types = set(g.objects(prop, RDF.type))
        types = {short_name(t) for t in types if str(t).startswith(str(OWL))}
        if not types:
            continue

        combo = "+".join(sorted(types))
        combo_counts_onto[combo] = combo_counts_onto.get(combo, 0) + 1
        combo_counts_global[combo] = combo_counts_global.get(combo, 0) + 1

    row = {"file": fname}
    row.update(combo_counts_onto)
    # row["SUMME"] = sum(combo_counts_onto.values())
    rows.append(row)

# DataFrame bauen
df = pd.DataFrame(rows).fillna(0).set_index("file")

# Summenzeile anhängen
# totals = {"file": "__TOTAL__"}
# for col in df.columns:
#     totals[col] = df[col].sum()
# df = pd.concat([df, pd.DataFrame([totals]).set_index("file")])

# Speichern
df.to_csv(OUT_CSV)
print(f"✅ Ergebnisse gespeichert in {OUT_CSV}")

df.head(10)



df = pd.read_csv(OUT_CSV)
N = len(df)

construct_cols = [c for c in df.columns if c not in ("file", "total", "SUMME")]

summary_rows = []
for col in construct_cols:
    vals = pd.to_numeric(df[col], errors="coerce").fillna(0).astype(int)
    total = int(vals.sum())
    ont_count = int((vals > 0).sum())
    percent = (ont_count / N * 100) if N else 0

    nonzero_vals = sorted(vals[vals > 0].tolist())
    if ont_count > 0:
        avg = float(vals[vals > 0].mean())
        med = float(vals[vals > 0].median())
        minv = min(nonzero_vals)
        avg_0 = float(vals[vals >= 0].mean())
        med_0 = float(vals[vals >= 0].median())
    else:
        avg = med = minv = avg_0 = med_0 = 0.0
        
    maxv = int(vals.max()) if len(vals) else 0

    summary_rows.append({
        "Construct": col,
        "Summe": total,
        "#Ontologien": ont_count,
        "%Ontologien": round(percent, 1),
        "Ø pro Ontologie (ohne 0)": round(avg, 2),
        "Ø pro Ontologie (mit 0)": round(avg_0, 2),
        "Median (ohne 0)": med,
        "Median (mit 0)": med_0,
        "Min (> 0)": minv,
        "Max": maxv,
        "Werte (> 0)": nonzero_vals,  # hier alle Werte explizit
        # "Werte (für Median mit 0)": sorted(vals.tolist())
    })

summary_df = pd.DataFrame(summary_rows).sort_values(by=["Summe", "#Ontologien"], ascending=False)
summary_df.to_csv(OUT_SUMMARY, index=False)

print(f"✅ Auswertung gespeichert: {OUT_SUMMARY}")
print("\nZusammenfassung:\n", summary_df)

In [8]:
# Anzahl InverseOf-Bezeihungen pro Property für Ontos mit owl:inverseOf
# Pfade
ONT_DIR = r"C:\Users\ilove\OneDrive\Uni\Master - Philipps Uni\Master Thesis\Ontologien\Zum Testen von Verteilungen von Konzepten\Bio Portal"
OUT_CSV = "Bio_Portal_ontology_inverseOf_distribution_full.csv"
OUT_SUMMARY = "Bio_Portal_ontology_inverseOf_distribution_summary.csv"

EXTS = (".owl", ".ttl", ".rdf", ".jsonld", ".nt", ".n3")

def count_inverse_of(g: Graph):
    """
    Gibt Dict {property: anzahl_inverse_properties} zurück.
    Zählt owl:inverseOf sowohl als Subjekt als auch als Objekt.
    """
    inverse_counts = {}

    # Property als Subjekt
    for prop, inv in g.subject_objects(OWL.inverseOf):
        inverse_counts.setdefault(prop, set()).add(inv)

    # Property als Objekt
    for inv, prop in g.subject_objects(OWL.inverseOf):
        inverse_counts.setdefault(prop, set()).add(inv)

    # In Zahlen umwandeln
    counts = {str(p): len(s) for p, s in inverse_counts.items()}
    return counts


# rows = []
# idx = 1

# for fname in sorted(os.listdir(ONT_DIR)):
#     if not fname.lower().endswith(EXTS):
#         continue

#     path = os.path.join(ONT_DIR, fname)
#     print(f"{idx}. {fname}")
#     idx += 1

#     try:
#         g = Graph()
#         g.parse(path)
#         inverse_counts = count_inverse_of(g)
#     except Exception as e:
#         print(f"   ⚠️ Fehler beim Parsen: {e}")
#         continue

#     # ❗ Überspringe Ontologien ohne inverseOf-Beziehungen
#     if not inverse_counts:
#         print(f"   ⏭️  Keine inverseOf-Beziehungen gefunden – wird übersprungen.")
#         continue

#     # Anzahl aller Properties (Object + Datatype)
#     all_props = set(g.subjects(RDF.type, OWL.ObjectProperty)) | set(g.subjects(RDF.type, OWL.DatatypeProperty))
#     num_all_props = len(all_props)

#     # Falls Property keine inverseOf hat → zähle als 0
#     props_with_inverse = set(inverse_counts.keys())
#     num_zero_inverse = num_all_props - len(props_with_inverse)

#     dist = Counter(inverse_counts.values())
#     dist[0] = dist.get(0, 0) + num_zero_inverse

#     # Umwandeln in Spaltennamen inverse_X
#     row = {"file": fname}
#     for k, v in sorted(dist.items()):
#         row[f"inverse_{k}"] = v

#     # SUMME (Anzahl aller Properties)
#     row["SUMME"] = sum(dist.values())
#     rows.append(row)

# # Falls gar keine Ontologien Inversen haben → abbrechen
# if not rows:
#     print("❌ Keine Ontologien mit inverseOf-Beziehungen gefunden!")
# else:
#     # DataFrame
#     df = pd.DataFrame(rows).fillna(0)
#     num_cols = [c for c in df.columns if c != "file"]
#     df[num_cols] = df[num_cols].astype(int)

#     # Speichern
#     df.to_csv(OUT_CSV, index=False)
#     print(f"✅ Ergebnisse gespeichert in {OUT_CSV}")
   
    
df = pd.read_csv(OUT_CSV)
N = len(df)

# Alle Konstruktspalten für die Auswertung:
# (Alles außer Datei-Name, _error und SUMME; Property-Typen bleiben drin – werden aber nicht zusammengezählt,
#  hier machen wir eine per-Konstrukt-Auswertung, also dürfen sie erscheinen.)
construct_cols = [c for c in df.columns if c not in ("file", "_error", "SUMME")]

summary_rows = []
for col in construct_cols:
    vals = pd.to_numeric(df[col], errors="coerce").fillna(0).astype(int)
    total = int(vals.sum())
    ont_count = int((vals > 0).sum())
    percent = (ont_count / N * 100) if N else 0

    nonzero_vals = sorted(vals[vals > 0].tolist())
    if ont_count > 0:
        avg = float(vals[vals > 0].mean())
        med = float(vals[vals > 0].median())
        minv = min(nonzero_vals)
        avg_0 = float(vals[vals >= 0].mean())
        med_0 = float(vals[vals >= 0].median())
    else:
        avg = med = minv = avg_0 = med_0 = 0.0
        
    maxv = int(vals.max()) if len(vals) else 0

    summary_rows.append({
        "Construct": col,
        "Summe": total,
        "#Ontologien": ont_count,
        "%Ontologien": round(percent, 1),
        "Ø pro Ontologie (ohne 0)": round(avg, 2),
        "Ø pro Ontologie (mit 0)": round(avg_0, 2),
        "Median (ohne 0)": med,
        "Median (mit 0)": med_0,
        "Min (>0)": minv,
        "Max": maxv,
        "Werte (für Median ohne 0)": nonzero_vals,  # hier alle Werte explizit
        # "Werte (für Median mit 0)": sorted(vals.tolist())
    })

summary_df = pd.DataFrame(summary_rows).sort_values(by=["Summe", "#Ontologien"], ascending=False)
summary_df.to_csv(OUT_SUMMARY, index=False)

print(f"✅ Auswertung gespeichert: {OUT_SUMMARY}")
summary_df

✅ Auswertung gespeichert: Bio_Portal_ontology_inverseOf_distribution_summary.csv

,Construct,Summe,#Ontologien,%Ontologien,Ø pro Ontologie (ohne 0),Ø pro Ontologie (mit 0),Median (ohne 0),Median (mit 0),Min (>0),Max,Werte (für Median ohne 0)
0,inverse_0,4384,28,93.3,156.57,146.13,137.5,119.5,6,606,"[6, 12, 19, 20, 28, 30, 45, 45, 52, 82, 85, 95..."
1,inverse_1,2645,30,100.0,88.17,88.17,67.0,67.0,2,333,"[2, 4, 8, 12, 24, 28, 34, 42, 44, 44, 50, 52, ..."
2,inverse_2,60,16,53.3,3.75,2.00,2.0,1.0,1,18,"[1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 4, 12,..."
5,inverse_3,2,2,6.7,1.00,0.07,1.0,0.0,1,1,"[1, 1]"
3,inverse_4,1,1,3.3,1.00,0.03,1.0,0.0,1,1,[1]
4,inverse_6,1,1,3.3,1.00,0.03,1.0,0.0,1,1,[1]

In [7]:
# rdf:type owl:Ontology
# 🔧 Pfade
ONT_DIR = r"C:\Users\ilove\OneDrive\Uni\Master - Philipps Uni\Master Thesis\Ontologien\Zum Testen von Verteilungen von Konzepten\Bio Portal"
OUT_CSV = "Bio_Portal_ontology_construct_counts_full_3.csv"
OUT_SUMMARY = "Bio_Portal_ontology_construct_counts_summary_3.csv"

# --- 1) Definition aller zu zählenden Konstrukte ---

# a) Dinge, die über rdf:type gezählt werden (Klassen/Konstrukte + Property-Eigenschaften!)
#    Manche OWL2-Varianten haben alternative Klassennamen (z. B. SymmetricObjectProperty).
TYPE_MULTI = {
    "owl:ontology": [OWL.Ontology ]   
}

# rdf:nil ist eine Ressource – wir zählen Vorkommen als Objekt separat
COUNT_RDF_NIL = True

# Welche Spalten NICHT in die SUMME eingehen (nur reporten)
EXCLUDE_FROM_SUM = {
    "owl:ObjectProperty",
    "owl:DatatypeProperty",
    "owl:AnnotationProperty",
    "rdf:Property",
    "owl:Class",
    "rdfs:Class"
}

EXTS = (".owl", ".ttl", ".rdf")

def count_in_graph(g: Graph) -> dict:
    counts = {}

    # rdf:type-basierte Zählungen (inkl. Property-Eigenschaften als Typ!)
    for label, class_list in TYPE_MULTI.items():
        total = 0
        for cls in class_list:
            total += sum(1 for _ in g.subjects(RDF.type, cls))
        counts[label] = total

    # # Prädikat-basierte Zählungen
    # for label, pred in PREDICATES.items():
    #     counts[label] = sum(1 for _ in g.triples((None, pred, None)))

    # # rdf:nil (als Objekt)
    # if COUNT_RDF_NIL:
    #     counts["rdf:nil (as object)"] = sum(1 for _ in g.triples((None, None, RDF.nil)))

    # SUMME (ohne die reinen Property-Typen)
    sum_keys = [k for k in counts.keys() if k not in EXCLUDE_FROM_SUM]
    counts["SUMME"] = sum(counts[k] for k in sum_keys if k != "SUMME")

    return counts

# --- 2) Dateien zählen & CSV mit allen Rohzahlen schreiben ---
rows = []
idx = 1
for fname in sorted(os.listdir(ONT_DIR)):
    print(f"{idx}. {fname}")
    if not fname.lower().endswith(EXTS):
        idx += 1
        continue

    path = os.path.join(ONT_DIR, fname)
    try:
        g = Graph()
        g.parse(path)
        c = count_in_graph(g)
    except Exception as e:
        # bei Fehlern alle Keys auf 0
        zero_keys = (
            list(TYPE_MULTI.keys())
            # + list(PREDICATES.keys())
            # + (["rdf:nil (as object)"] if COUNT_RDF_NIL else [])
            # + ["SUMME"]
            # + list(PREDICATES.keys())
        )
        c = {k: 0 for k in zero_keys}
        c["_error"] = str(e)

    row = {"file": fname, **c}
    print(f"    {row}")
    rows.append(row)
    idx += 1

# Spaltenreihenfolge
columns = (
    ["file"]
    + list(TYPE_MULTI.keys())
    # + list(PREDICATES.keys())
    # + (["rdf:nil (as object)"] if COUNT_RDF_NIL else [])
    # + ["SUMME"]
)
if any("_error" in r for r in rows):
    columns += ["_error"]

df = pd.DataFrame(rows, columns=columns)
df.to_csv(OUT_CSV, index=False)
print(f"✅ Rohzahlen gespeichert: {OUT_CSV}")

# --- 3) Auswertungstabelle (Summe, #Ontologien, %Ontologien, Ø, Median, Max) ---

# __TOTAL__ Zeilen gibt's hier nicht; wir nehmen direkt df
df = pd.read_csv(OUT_CSV)
N = len(df)

# Alle Konstruktspalten für die Auswertung:
# (Alles außer Datei-Name, _error und SUMME; Property-Typen bleiben drin – werden aber nicht zusammengezählt,
#  hier machen wir eine per-Konstrukt-Auswertung, also dürfen sie erscheinen.)
construct_cols = [c for c in df.columns if c not in ("file", "_error", "SUMME")]

summary_rows = []
for col in construct_cols:
    vals = pd.to_numeric(df[col], errors="coerce").fillna(0).astype(int)
    total = int(vals.sum())
    ont_count = int((vals > 0).sum())
    percent = (ont_count / N * 100) if N else 0

    nonzero_vals = sorted(vals[vals > 0].tolist())
    if ont_count > 0:
        avg = float(vals[vals > 0].mean())
        med = float(vals[vals > 0].median())
        minv = min(nonzero_vals)
        avg_0 = float(vals[vals >= 0].mean())
        med_0 = float(vals[vals >= 0].median())
    else:
        avg = med = minv = avg_0 = med_0 = 0.0
        
    maxv = int(vals.max()) if len(vals) else 0

    summary_rows.append({
        "Construct": col,
        "Summe": total,
        "#Ontologien": ont_count,
        "%Ontologien": round(percent, 1),
        "Ø pro Ontologie (ohne 0)": round(avg, 2),
        "Ø pro Ontologie (mit 0)": round(avg_0, 2),
        "Median (ohne 0)": med,
        "Median (mit 0)": med_0,
        "Min (>0)": minv,
        "Max": maxv,
        "Werte (für Median ohne 0)": nonzero_vals,  # hier alle Werte explizit
        "Werte (für Median mit 0)": sorted(vals.tolist())
    })

summary_df = pd.DataFrame(summary_rows).sort_values(by=["Summe", "#Ontologien"], ascending=False)
summary_df.to_csv(OUT_SUMMARY, index=False)

print(f"✅ Auswertung gespeichert: {OUT_SUMMARY}")
summary_df

1. Allergidoc.rdf
    {'file': 'Allergidoc.rdf', 'owl:ontology': 1, 'SUMME': 1}
2. BMONT.owl
    {'file': 'BMONT.owl', 'owl:ontology': 1, 'SUMME': 1}
3. CDMOnto.owl
    {'file': 'CDMOnto.owl', 'owl:ontology': 1, 'SUMME': 1}
4. COPPER.owl
    {'file': 'COPPER.owl', 'owl:ontology': 1, 'SUMME': 1}
5. CTCAE_5.0.owl
    {'file': 'CTCAE_5.0.owl', 'owl:ontology': 1, 'SUMME': 1}
6. DMDSONT.rdf
    {'file': 'DMDSONT.rdf', 'owl:ontology': 1, 'SUMME': 1}
7. EDAM.owl
    {'file': 'EDAM.owl', 'owl:ontology': 1, 'SUMME': 1}
8. GAMUTS.owl
    {'file': 'GAMUTS.owl', 'owl:ontology': 1, 'SUMME': 1}
9. O3_20250709.owl
    {'file': 'O3_20250709.owl', 'owl:ontology': 1, 'SUMME': 1}
10. OBOREL.owl
    {'file': 'OBOREL.owl', 'owl:ontology': 1, 'SUMME': 1}
11. OntoCaimerV2-Joe-Mary.owl
    {'file': 'OntoCaimerV2-Joe-Mary.owl', 'owl:ontology': 1, 'SUMME': 1}
12. Ontos mit InverseOf
13. Ontos mit PropertyChainAxiom
14. bbo.rdf
    {'file': 'bbo.rdf', 'owl:ontology': 1, 'SUMME': 1}
15. bcio.owl
    {'file': 'bcio.owl', 'owl:ontology': 1, 'SUMME': 1}
16. bervo.owl
    {'file': 'bervo.owl', 'owl:ontology': 1, 'SUMME': 1}
17. cl.owl
    {'file': 'cl.owl', 'owl:ontology': 1, 'SUMME': 1}
18. clo_merged.owl
    {'file': 'clo_merged.owl', 'owl:ontology': 1, 'SUMME': 1}
19. cob.owl
    {'file': 'cob.owl', 'owl:ontology': 1, 'SUMME': 1}
20. envo.owl
    {'file': 'envo.owl', 'owl:ontology': 1, 'SUMME': 1}
21. evora_ontology.ttl
    {'file': 'evora_ontology.ttl', 'owl:ontology': 1, 'SUMME': 1}
22. foodon.owl
    {'file': 'foodon.owl', 'owl:ontology': 1, 'SUMME': 1}
23. fypo.owl
    {'file': 'fypo.owl', 'owl:ontology': 1, 'SUMME': 1}
24. gbol-ontology.ttl
    {'file': 'gbol-ontology.ttl', 'owl:ontology': 1, 'SUMME': 1}
25. hhear_properties.rdf
    {'file': 'hhear_properties.rdf', 'owl:ontology': 1, 'SUMME': 1}
26. hso.owl
    {'file': 'hso.owl', 'owl:ontology': 1, 'SUMME': 1}
27. jfo_v005.ttl
    {'file': 'jfo_v005.ttl', 'owl:ontology': 1, 'SUMME': 1}
28. meo.v.1.0.ttl
    {'file': 'meo.v.1.0.ttl', 'owl:ontology': 1, 'SUMME': 1}
29. metpo.owl
    {'file': 'metpo.owl', 'owl:ontology': 1, 'SUMME': 1}
30. mro.owl
    {'file': 'mro.owl', 'owl:ontology': 1, 'SUMME': 1}
31. mwo.owl
    {'file': 'mwo.owl', 'owl:ontology': 1, 'SUMME': 1}
32. namo.owl.ttl
    {'file': 'namo.owl.ttl', 'owl:ontology': 1, 'SUMME': 1}
33. nando_2025-08-26.ttl
    {'file': 'nando_2025-08-26.ttl', 'owl:ontology': 1, 'SUMME': 1}
34. nochmal
35. oae_merged.owl
    {'file': 'oae_merged.owl', 'owl:ontology': 1, 'SUMME': 1}
36. oba.owl
    {'file': 'oba.owl', 'owl:ontology': 1, 'SUMME': 1}
37. obi.owl
    {'file': 'obi.owl', 'owl:ontology': 1, 'SUMME': 1}
38. odfa.owl
    {'file': 'odfa.owl', 'owl:ontology': 1, 'SUMME': 1}
39. ordo_orphanet.owl
    {'file': 'ordo_orphanet.owl', 'owl:ontology': 1, 'SUMME': 1}
40. pato.owl
    {'file': 'pato.owl', 'owl:ontology': 1, 'SUMME': 1}
41. pcl.owl
    {'file': 'pcl.owl', 'owl:ontology': 1, 'SUMME': 1}
42. phases.owl
    {'file': 'phases.owl', 'owl:ontology': 1, 'SUMME': 1}
43. phipo.owl
    {'file': 'phipo.owl', 'owl:ontology': 1, 'SUMME': 1}
44. plantso.owl
    {'file': 'plantso.owl', 'owl:ontology': 1, 'SUMME': 1}
45. psdo.rdf
    {'file': 'psdo.rdf', 'owl:ontology': 1, 'SUMME': 1}
46. rbo.owl
    {'file': 'rbo.owl', 'owl:ontology': 1, 'SUMME': 1}
47. sio-release.owl
    {'file': 'sio-release.owl', 'owl:ontology': 1, 'SUMME': 1}
48. sleep.rdf
    {'file': 'sleep.rdf', 'owl:ontology': 1, 'SUMME': 1}
49. slso.owl
    {'file': 'slso.owl', 'owl:ontology': 1, 'SUMME': 1}
50. ssbd_v20250512.ttl
    {'file': 'ssbd_v20250512.ttl', 'owl:ontology': 1, 'SUMME': 1}
51. tara-acupoints-inferred.rdf
    {'file': 'tara-acupoints-inferred.rdf', 'owl:ontology': 1, 'SUMME': 1}
52. uberon.owl
    {'file': 'uberon.owl', 'owl:ontology': 1, 'SUMME': 1}
53. with imports
54. xpo.owl
    {'file': 'xpo.owl', 'owl:ontology': 1, 'SUMME': 1}
✅ Rohzahlen gespeichert: Bio_Portal_ontology_construct_counts_full_3.csv
✅ Auswertung gespeichert: Bio_Portal_ontology_construct_counts_summary_3.csv

,Construct,Summe,#Ontologien,%Ontologien,Ø pro Ontologie (ohne 0),Ø pro Ontologie (mit 0),Median (ohne 0),Median (mit 0),Min (>0),Max,Werte (für Median ohne 0),Werte (für Median mit 0)
0,owl:ontology,50,50,100.0,1.0,1.0,1.0,1.0,1,1,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."

In [19]:
# Anzahl Superproperties pro Property 
# Ordner + Ausgabe
ONT_DIR = r"C:\Users\ilove\OneDrive\Uni\Master - Philipps Uni\Master Thesis\Ontologien\Zum Testen von Verteilungen von Konzepten\Bio Portal\nochmal"
OUT_CSV = "Bio_Portal_ontology_super_property_distribution_full_2.csv"
OUT_SUMMARY = "Bio_Portal_ontology_super_property_distribution_summary_2.csv"

EXTS = (".owl", ".ttl", ".rdf", ".jsonld", ".nt", ".n3")

# def superproperty_counts(g: Graph) -> dict[str, int]:
#     """
#     Liefert { property_iri_str: anzahl_direkter_superproperties }.
#     Property-Menge = Subj∪Obj von rdfs:subPropertyOf ∪ getypte Properties.
#     Zählt nur direkte Superproperties (keine transitiven Ketten).
#     """
#     # 1) Alle subPropertyOf-Kanten einsammeln
#     supersets = defaultdict(set)  # prop -> set(superprops)
#     all_props = set()

#     for s, _, o in g.triples((None, RDFS.subPropertyOf, None)):
#         # nur URI-Properties berücksichtigen (Blank Nodes überspringen)
#         if (s, RDF.type, OWL.AnnotationProperty) in g or (o, RDF.type, OWL.AnnotationProperty) in g:
#             continue
        
#         if isinstance(s, URIRef):
#             all_props.add(s)
#         if isinstance(o, URIRef):
#             all_props.add(o)
#         if isinstance(s, URIRef) and isinstance(o, URIRef):
#             supersets[s].add(o)

#     # 2) alle getypten Properties hinzufügen (falls noch nicht drin)
#     typed_props = (
#         set(g.subjects(RDF.type, OWL.ObjectProperty)) |
#         set(g.subjects(RDF.type, OWL.DatatypeProperty)) #|
#         # set(g.subjects(RDF.type, OWL.AnnotationProperty))
#     )
#     all_props |= {p for p in typed_props if isinstance(p, URIRef)}

#     # 3) Zählung erstellen (distinct Superproperties)
#     counts = {str(p): len(supersets.get(p, set())) for p in all_props}
#     return counts

# rows = []
# idx = 1
# for fname in sorted(os.listdir(ONT_DIR)):
#     if not fname.lower().endswith(EXTS):
#         continue
#     path = os.path.join(ONT_DIR, fname)
#     print(f"{idx}. {fname}")
#     idx += 1

#     try:
#         g = Graph()
#         g.parse(path)
#     except Exception as e:
#         print(f"   ⚠️ Parse-Fehler: {e}")
#         continue

#     counts = superproperty_counts(g)

#     # Verteilung: wie viele Properties haben 0,1,2,... Superproperties?
#     dist = Counter(counts.values())
#     row = {"file": fname, "SUMME": sum(dist.values())}
#     for k in sorted(dist.keys()):
#         row[f"super_{k}"] = dist[k]
#     rows.append(row)

# # DataFrame bauen
# df = pd.DataFrame(rows).fillna(0)

# # numerische Spalten korrekt als int
# num_cols = [c for c in df.columns if c != "file"]
# df[num_cols] = df[num_cols].astype(int)

# # Summenzeile über alle Ontologien
# # totals = {"file": "__TOTAL__"}
# # for c in num_cols:
# #     totals[c] = df[c].sum()
# # df = pd.concat([df, pd.DataFrame([totals])], ignore_index=True)

# df.to_csv(OUT_CSV, index=False)
# print(f"✅ Verteilungen gespeichert in {OUT_CSV}")
# df.head()


df = pd.read_csv(OUT_CSV)
N = len(df)

# Alle Konstruktspalten für die Auswertung:
# (Alles außer Datei-Name, _error und SUMME; Property-Typen bleiben drin – werden aber nicht zusammengezählt,
#  hier machen wir eine per-Konstrukt-Auswertung, also dürfen sie erscheinen.)
construct_cols = [c for c in df.columns if c not in ("file", "_error", "SUMME")]

summary_rows = []
for col in construct_cols:
    vals = pd.to_numeric(df[col], errors="coerce").fillna(0).astype(int)
    total = int(vals.sum())
    ont_count = int((vals > 0).sum())
    percent = (ont_count / N * 100) if N else 0

    nonzero_vals = sorted(vals[vals > 0].tolist())
    if ont_count > 0:
        avg = float(vals[vals > 0].mean())
        med = float(vals[vals > 0].median())
        minv = min(nonzero_vals)
        avg_0 = float(vals[vals >= 0].mean())
        med_0 = float(vals[vals >= 0].median())
    else:
        avg = med = minv = avg_0 = med_0 = 0.0
        
    maxv = int(vals.max()) if len(vals) else 0

    summary_rows.append({
        "Construct": col,
        "Summe": total,
        "#Ontologien": ont_count,
        "%Ontologien": round(percent, 1),
        "Ø pro Ontologie (ohne 0)": round(avg, 2),
        "Ø pro Ontologie (mit 0)": round(avg_0, 2),
        "Median (ohne 0)": med,
        "Median (mit 0)": med_0,
        "Min (>0)": minv,
        "Max": maxv,
        "Werte (für Median ohne 0)": nonzero_vals, 
    })

summary_df = pd.DataFrame(summary_rows).sort_values(by=["Summe", "#Ontologien"], ascending=False)
summary_df.to_csv(OUT_SUMMARY, index=False)

print(f"✅ Auswertung gespeichert: {OUT_SUMMARY}")
summary_df

✅ Auswertung gespeichert: Bio_Portal_ontology_super_property_distribution_summary_2.csv

,Construct,Summe,#Ontologien,%Ontologien,Ø pro Ontologie (ohne 0),Ø pro Ontologie (mit 0),Median (ohne 0),Median (mit 0),Min (>0),Max,Werte (für Median ohne 0)
1,super_1,3604,35,70.0,102.97,72.08,84.0,43.0,1,481,"[1, 1, 2, 4, 10, 16, 17, 18, 42, 42, 44, 49, 5..."
0,super_0,3486,47,94.0,74.17,69.72,45.0,43.0,1,566,"[1, 2, 2, 3, 3, 4, 4, 5, 5, 5, 5, 9, 12, 13, 1..."
2,super_2,713,23,46.0,31.00,14.26,30.0,0.0,1,105,"[1, 2, 2, 2, 2, 7, 7, 7, 11, 27, 28, 30, 37, 4..."
3,super_3,54,17,34.0,3.18,1.08,3.0,0.0,1,5,"[1, 1, 2, 2, 2, 2, 2, 3, 3, 4, 4, 4, 4, 5, 5, ..."

In [ ]:
# Anzahl Subproperties pro Property

# Ordner + Ausgabe
ONT_DIR = r"C:\Users\ilove\OneDrive\Uni\Master - Philipps Uni\Master Thesis\Ontologien\Zum Testen von Verteilungen von Konzepten\Bio Portal"
OUT_CSV = "Bio_Portal_ontology_sub_property_distribution_full.csv"
OUT_SUMMARY = "Bio_Portal_ontology_sub_property_distribution_summary.csv"

EXTS = (".owl", ".ttl", ".rdf", ".jsonld", ".nt", ".n3")

def superproperty_counts(g: Graph) -> dict[str, int]:
    """
    Liefert { property_iri_str: anzahl_direkter_superproperties }.
    Property-Menge = Subj∪Obj von rdfs:subPropertyOf ∪ getypte Properties.
    Zählt nur direkte Superproperties (keine transitiven Ketten).
    """
    # 1) Alle subPropertyOf-Kanten einsammeln
    subsets = defaultdict(set)  # prop -> set(superprops)
    all_props = set()

    for s, _, o in g.triples((None, RDFS.subPropertyOf, None)):
        # nur URI-Properties berücksichtigen (Blank Nodes überspringen)
        if (s, RDF.type, OWL.AnnotationProperty) in g or (o, RDF.type, OWL.AnnotationProperty) in g:
            continue
        
        if isinstance(s, URIRef):
            all_props.add(s)
        if isinstance(o, URIRef):
            all_props.add(o)
        if isinstance(s, URIRef) and isinstance(o, URIRef):
            subsets[o].add(s)

    # 2) alle getypten Properties hinzufügen (falls noch nicht drin)
    typed_props = (
        set(g.subjects(RDF.type, OWL.ObjectProperty)) |
        set(g.subjects(RDF.type, OWL.DatatypeProperty)) #|
        # set(g.subjects(RDF.type, OWL.AnnotationProperty))
    )
    all_props |= {p for p in typed_props if isinstance(p, URIRef)}

    # 3) Zählung erstellen (distinct Superproperties)
    counts = {str(p): len(subsets.get(p, set())) for p in all_props}
    return counts

rows = []
idx = 1
for fname in sorted(os.listdir(ONT_DIR)):
    if not fname.lower().endswith(EXTS):
        continue
    path = os.path.join(ONT_DIR, fname)
    print(f"{idx}. {fname}")
    idx += 1

    try:
        g = Graph()
        g.parse(path)
    except Exception as e:
        print(f"   ⚠️ Parse-Fehler: {e}")
        continue

    counts = superproperty_counts(g)

    # Verteilung: wie viele Properties haben 0,1,2,... Superproperties?
    dist = Counter(counts.values())
    row = {"file": fname, "SUMME": sum(dist.values())}
    for k in sorted(dist.keys()):
        row[f"sub_{k}"] = dist[k]
    rows.append(row)

# DataFrame bauen
df = pd.DataFrame(rows).fillna(0)

# numerische Spalten korrekt als int
num_cols = [c for c in df.columns if c != "file"]
df[num_cols] = df[num_cols].astype(int)

# # Summenzeile über alle Ontologien
# totals = {"file": "__TOTAL__"}
# for c in num_cols:
#     totals[c] = df[c].sum()
# df = pd.concat([df, pd.DataFrame([totals])], ignore_index=True)

df.to_csv(OUT_CSV, index=False)
print(f"✅ Verteilungen gespeichert in {OUT_CSV}")
df.head(10)


# __TOTAL__ Zeilen gibt's hier nicht; wir nehmen direkt df
df = pd.read_csv(OUT_CSV)
N = len(df)

# Alle Konstruktspalten für die Auswertung:
# (Alles außer Datei-Name, _error und SUMME; Property-Typen bleiben drin – werden aber nicht zusammengezählt,
#  hier machen wir eine per-Konstrukt-Auswertung, also dürfen sie erscheinen.)
construct_cols = [c for c in df.columns if c not in ("file", "_error", "SUMME")]

summary_rows = []
for col in construct_cols:
    vals = pd.to_numeric(df[col], errors="coerce").fillna(0).astype(int)
    total = int(vals.sum())
    ont_count = int((vals > 0).sum())
    percent = (ont_count / N * 100) if N else 0

    nonzero_vals = sorted(vals[vals > 0].tolist())
    if ont_count > 0:
        avg = float(vals[vals > 0].mean())
        med = float(vals[vals > 0].median())
        minv = min(nonzero_vals)
        avg_0 = float(vals[vals >= 0].mean())
        med_0 = float(vals[vals >= 0].median())
    else:
        avg = med = minv = avg_0 = med_0 = 0.0
        
    maxv = int(vals.max()) if len(vals) else 0

    summary_rows.append({
        "Construct": col,
        "Summe": total,
        "#Ontologien": ont_count,
        "%Ontologien": round(percent, 1),
        "Ø pro Ontologie (ohne 0)": round(avg, 2),
        "Ø pro Ontologie (mit 0)": round(avg_0, 2),
        "Median (ohne 0)": med,
        "Median (mit 0)": med_0,
        "Min (>0)": minv,
        "Max": maxv,
        "Werte (für Median ohne 0)": nonzero_vals,  # hier alle Werte explizit
        "Werte (für Median mit 0)": sorted(vals.tolist())
    })

summary_df = pd.DataFrame(summary_rows).sort_values(by=["Summe", "#Ontologien"], ascending=False)
summary_df.to_csv(OUT_SUMMARY, index=False)

print(f"✅ Auswertung gespeichert: {OUT_SUMMARY}")
summary_df.head(10)

In [12]:
# Zählt komplexe vs simple Klassen

# --- Pfade ---
ONT_DIR = r"C:\Users\ilove\OneDrive\Uni\Master - Philipps Uni\Master Thesis\Ontologien\Zum Testen von Verteilungen von Konzepten\Bio Portal"
OUT_CSV = "Bio_Portal_ontology_class_complexity_counts_full4.csv"
OUT_SUMMARY = "Bio_Portal_ontology_class_complexity_counts_summary4.csv"
# ONT_DIR = r"C:\Users\ilove\OneDrive\Uni\Master - Philipps Uni\Master Thesis\geo_all"
# OUT_CSV = "geo_all_construct_complex_vs_simple_class2.csv"

EXTS = (".owl", ".ttl", ".rdf", ".jsonld", ".nt", ".n3")

def complex_class_definitions(g: Graph):
    """Zählt Klassen, die durch komplexe (BNode-basierte) Beschreibungen definiert sind."""
    
    # Alle expliziten Klassen (rdf:type owl:Class)
    all_classes = set(c for c in g.subjects(RDF.type, OWL.Class) if isinstance(c, URIRef))
    
    # --- Kategorien ---
    subclass_complex = {s for s, _, o in g.triples((None, RDFS.subClassOf, None)) if isinstance(o, BNode)}
    subclass_simple = {s for s, _, o in g.triples((None, RDFS.subClassOf, None)) if not isinstance(o, BNode)}
    equivalent_complex = ({s for s, _, o in g.triples((None, OWL.equivalentClass, None)) if isinstance(o, BNode)})
    equivalent_simple = ({s for s, _, o in g.triples((None, OWL.equivalentClass, None)) if not isinstance(o, BNode)})
    disjoint_complex = ({s for s, _, o in g.triples((None, OWL.disjointWith, None)) if isinstance(o, BNode)})
    disjoint_simple = ({s for s, _, o in g.triples((None, OWL.disjointWith, None)) if not isinstance(o, BNode)})

    # --- Gesamtmenge komplex definierter Klassen ---
    complex_classes = subclass_complex | equivalent_complex | disjoint_complex

    simple_classes = {c for c in all_classes if c not in complex_classes and not isinstance(c, BNode)}

    return {
        "subClassOf_complex": len(subclass_complex),
        "subClassOf_simple": len(subclass_simple),
        "equivalentClass_complex": len(equivalent_complex),
        "equivalentClass_simple": len(equivalent_simple),
        "disjoint_complex": len(disjoint_complex),
        "disjoint_simple": len(disjoint_simple),
        "complex_total": len(complex_classes),
        "simple_total": len(simple_classes),
        "total_classes": len(all_classes),
    }

# --- Verarbeitung aller Ontologien ---
rows = []
idx = 1

for fname in sorted(os.listdir(ONT_DIR)):
    if not fname.lower().endswith(EXTS):
        continue

    path = os.path.join(ONT_DIR, fname)
    print(f"{idx}. {fname}")
    idx += 1

    try:
        g = Graph()
        g.parse(path)
        stats = complex_class_definitions(g)
    except Exception as e:
        print(f"   ⚠️ Fehler beim Parsen: {e}")
        stats = {k: 0 for k in ["subClassOf_complex", "equivalentClass_complex",
                                "disjoint_complex", "complex_total","simple_classes", "total_classes"]}
        stats["_error"] = str(e)

    row = {"file": fname, **stats}
    rows.append(row)

# --- DataFrame & Summenzeile ---
df = pd.DataFrame(rows).fillna(0)
# totals = {"file": "__TOTAL__"}
# for c in df.columns:
#     if c == "file":
#         continue
#     totals[c] = df[c].sum() if pd.api.types.is_numeric_dtype(df[c]) else ""
# df = pd.concat([df, pd.DataFrame([totals])], ignore_index=True)

# --- Speichern ---
df.to_csv(OUT_CSV, index=False)
print(f"✅ Ergebnisse gespeichert in {OUT_CSV}")
df.head(15)

# __TOTAL__ Zeilen gibt's hier nicht; wir nehmen direkt df
df = pd.read_csv(OUT_CSV)
N = len(df)

# Alle Konstruktspalten für die Auswertung:
# (Alles außer Datei-Name, _error und SUMME; Property-Typen bleiben drin – werden aber nicht zusammengezählt,
#  hier machen wir eine per-Konstrukt-Auswertung, also dürfen sie erscheinen.)
construct_cols = [c for c in df.columns if c not in ("file", "_error", "SUMME")]

summary_rows = []
for col in construct_cols:
    vals = pd.to_numeric(df[col], errors="coerce").fillna(0).astype(int)
    total = int(vals.sum())
    ont_count = int((vals > 0).sum())
    percent = (ont_count / N * 100) if N else 0

    nonzero_vals = sorted(vals[vals > 0].tolist())
    if ont_count > 0:
        avg = float(vals[vals > 0].mean())
        med = float(vals[vals > 0].median())
        minv = min(nonzero_vals)
        avg_0 = float(vals[vals >= 0].mean())
        med_0 = float(vals[vals >= 0].median())
    else:
        avg = med = minv = avg_0 = med_0 = 0.0
        
    maxv = int(vals.max()) if len(vals) else 0

    summary_rows.append({
        "Construct": col,
        "Summe": total,
        "#Ontologien": ont_count,
        "%Ontologien": round(percent, 1),
        "Ø pro Ontologie (ohne 0)": round(avg, 2),
        "Ø pro Ontologie (mit 0)": round(avg_0, 2),
        "Median (ohne 0)": med,
        "Median (mit 0)": med_0,
        "Min (>0)": minv,
        "Max": maxv,
        "Werte (für Median ohne 0)": nonzero_vals,  # hier alle Werte explizit
        "Werte (für Median mit 0)": sorted(vals.tolist())
    })

summary_df = pd.DataFrame(summary_rows).sort_values(by=["Summe", "#Ontologien"], ascending=False)
summary_df.to_csv(OUT_SUMMARY, index=False)

print(f"✅ Auswertung gespeichert: {OUT_SUMMARY}")
summary_df

1. Allergidoc.rdf
2. BMONT.owl
3. CDMOnto.owl
4. COPPER.owl
5. CTCAE_5.0.owl
6. DMDSONT.rdf
7. EDAM.owl
8. GAMUTS.owl
9. O3_20250709.owl
10. OBOREL.owl
11. OntoCaimerV2-Joe-Mary.owl
12. bbo.rdf
13. bcio.owl
14. bervo.owl
15. cl.owl
16. clo_merged.owl
17. cob.owl
18. envo.owl
19. evora_ontology.ttl
20. foodon.owl
21. fypo.owl
22. gbol-ontology.ttl
23. hhear_properties.rdf
24. hso.owl
25. jfo_v005.ttl
26. meo.v.1.0.ttl
27. metpo.owl
28. mro.owl
29. mwo.owl
30. namo.owl.ttl
31. nando_2025-08-26.ttl
32. oae_merged.owl
33. oba.owl
34. obi.owl
35. odfa.owl
36. ordo_orphanet.owl
37. pato.owl
38. pcl.owl
39. phases.owl
40. phipo.owl
41. plantso.owl
42. psdo.rdf
43. rbo.owl
44. sio-release.owl
45. sleep.rdf
46. slso.owl
47. ssbd_v20250512.ttl
48. tara-acupoints-inferred.rdf
49. uberon.owl
50. xpo.owl
✅ Ergebnisse gespeichert in Bio_Portal_ontology_class_complexity_counts_full4.csv
✅ Auswertung gespeichert: Bio_Portal_ontology_class_complexity_counts_summary4.csv

,Construct,Summe,#Ontologien,%Ontologien,Ø pro Ontologie (ohne 0),Ø pro Ontologie (mit 0),Median (ohne 0),Median (mit 0),Min (>0),Max,Werte (für Median ohne 0),Werte (für Median mit 0)
8,total_classes,456229,50,100.0,9124.58,9124.58,2488.5,2488.5,8,72730,"[8, 45, 56, 68, 77, 176, 183, 199, 230, 302, 3...","[8, 45, 56, 68, 77, 176, 183, 199, 230, 302, 3..."
1,subClassOf_simple,446387,49,98.0,9109.94,8927.74,2519.0,2509.0,30,72614,"[30, 48, 53, 76, 175, 181, 195, 264, 294, 294,...","[0, 30, 48, 53, 76, 175, 181, 195, 264, 294, 2..."
6,complex_total,290580,42,84.0,6918.57,5811.60,530.5,213.0,7,71294,"[7, 8, 18, 19, 28, 46, 47, 47, 55, 58, 61, 62,...","[0, 0, 0, 0, 0, 0, 0, 0, 7, 8, 18, 19, 28, 46,..."
0,subClassOf_complex,236639,42,84.0,5634.26,4732.78,370.0,169.0,7,55252,"[7, 8, 13, 16, 28, 37, 45, 45, 46, 47, 51, 61,...","[0, 0, 0, 0, 0, 0, 0, 0, 7, 8, 13, 16, 28, 37,..."
2,equivalentClass_complex,180746,32,64.0,5648.31,3614.92,427.0,18.5,2,56645,"[2, 3, 3, 7, 14, 17, 18, 19, 20, 33, 50, 85, 1...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
7,simple_total,172351,50,100.0,3447.02,3447.02,2079.5,2079.5,8,28995,"[8, 17, 30, 39, 49, 115, 128, 165, 184, 199, 2...","[8, 17, 30, 39, 49, 115, 128, 165, 184, 199, 2..."
4,disjoint_complex,3078,17,34.0,181.06,61.56,4.0,0.0,2,2454,"[2, 2, 2, 2, 2, 3, 3, 4, 4, 6, 15, 21, 23, 125...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
5,disjoint_simple,1814,28,56.0,64.79,36.28,23.0,2.5,1,624,"[1, 1, 2, 3, 3, 6, 8, 8, 8, 8, 14, 14, 17, 23,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,equivalentClass_simple,120,15,30.0,8.00,2.40,2.0,0.0,1,87,"[1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 3, 3, 5, 9, 87]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [ ]:
# Anzahl Funktionaler Properties je Property Type
# Pfade
ONT_DIR = r"C:\Users\ilove\OneDrive\Uni\Master - Philipps Uni\Master Thesis\Ontologien\Zum Testen von Verteilungen von Konzepten\Bio Portal"
OUT_CSV = "Bio_Portal_ontology_functional_properties_full.csv"
OUT_SUMMARY = "Bio_Portal_ontology_functional_properties_summary.csv"

EXTS = (".owl", ".ttl", ".rdf", ".jsonld", ".nt", ".n3")

def count_functional_properties(g: Graph):
    """Zählt Object/Datatype Properties und wie viele davon funktional sind."""

    # --- Alle Property-Typen ---
    obj_props = {p for p in g.subjects(RDF.type, OWL.ObjectProperty)}
    dt_props = {p for p in g.subjects(RDF.type, OWL.DatatypeProperty)}

    # --- Alle funktionalen Properties ---
    func_props = {p for p in g.subjects(RDF.type, OWL.FunctionalProperty)}

    # --- Schnittmengen ---
    object_functional = len(obj_props & func_props)
    datatype_functional = len(dt_props & func_props)

    return {
        "object_properties_total": len(obj_props),
        "datatype_properties_total": len(dt_props),
        "object_functional": object_functional,
        "datatype_functional": datatype_functional,
        "functional_total": object_functional + datatype_functional,
        "properties_total": len(obj_props) + len(dt_props),
    }

# --- Verarbeitung aller Ontologien ---
rows = []
idx = 1

for fname in sorted(os.listdir(ONT_DIR)):
    if not fname.lower().endswith(EXTS):
        continue

    path = os.path.join(ONT_DIR, fname)
    print(f"{idx}. {fname}")
    idx += 1

    try:
        g = Graph()
        g.parse(path)
        stats = count_functional_properties(g)
    except Exception as e:
        print(f"   ⚠️ Fehler beim Parsen: {e}")
        stats = {
            "object_properties_total": 0,
            "datatype_properties_total": 0,
            "object_functional": 0,
            "datatype_functional": 0,
            "functional_total": 0,
            "properties_total": 0,
            "_error": str(e),
        }

    row = {"file": fname, **stats}
    rows.append(row)

# --- DataFrame ---
df = pd.DataFrame(rows).fillna(0)
df.to_csv(OUT_CSV, index=False)

print(f"✅ Ergebnisse gespeichert in {OUT_CSV}")
df.head(10)
   
    
df = pd.read_csv(OUT_CSV)
N = len(df)

# Alle Konstruktspalten für die Auswertung:
# (Alles außer Datei-Name, _error und SUMME; Property-Typen bleiben drin – werden aber nicht zusammengezählt,
#  hier machen wir eine per-Konstrukt-Auswertung, also dürfen sie erscheinen.)
construct_cols = [c for c in df.columns if c not in ("file", "_error", "SUMME")]

summary_rows = []
for col in construct_cols:
    vals = pd.to_numeric(df[col], errors="coerce").fillna(0).astype(int)
    total = int(vals.sum())
    ont_count = int((vals > 0).sum())
    percent = (ont_count / N * 100) if N else 0

    nonzero_vals = sorted(vals[vals > 0].tolist())
    if ont_count > 0:
        avg = float(vals[vals > 0].mean())
        med = float(vals[vals > 0].median())
        minv = min(nonzero_vals)
        avg_0 = float(vals[vals >= 0].mean())
        med_0 = float(vals[vals >= 0].median())
    else:
        avg = med = minv = avg_0 = med_0 = 0.0
        
    maxv = int(vals.max()) if len(vals) else 0

    summary_rows.append({
        "Construct": col,
        "Summe": total,
        "#Ontologien": ont_count,
        "%Ontologien": round(percent, 1),
        "Ø pro Ontologie (ohne 0)": round(avg, 2),
        "Ø pro Ontologie (mit 0)": round(avg_0, 2),
        "Median (ohne 0)": med,
        "Median (mit 0)": med_0,
        "Min (>0)": minv,
        "Max": maxv,
        "Werte (für Median ohne 0)": nonzero_vals,  # hier alle Werte explizit
        # "Werte (für Median mit 0)": sorted(vals.tolist())
    })

summary_df = pd.DataFrame(summary_rows).sort_values(by=["Summe", "#Ontologien"], ascending=False)
summary_df.to_csv(OUT_SUMMARY, index=False)

print(f"✅ Auswertung gespeichert: {OUT_SUMMARY}")
summary_df

1. Allergidoc.rdf
2. BMONT.owl
3. CDMOnto.owl
4. COPPER.owl
5. CTCAE_5.0.owl
6. DMDSONT.rdf
7. EDAM.owl
8. GAMUTS.owl
9. O3_20250709.owl
10. OBOREL.owl
11. OntoCaimerV2-Joe-Mary.owl
12. bbo.rdf
13. bcio.owl
14. bervo.owl
15. cl.owl
16. clo_merged.owl
17. cob.owl
18. envo.owl
19. evora_ontology.ttl
20. foodon.owl
21. fypo.owl
22. gbol-ontology.ttl
23. hhear_properties.rdf
24. hso.owl
25. jfo_v005.ttl
26. meo.v.1.0.ttl
27. metpo.owl
28. mro.owl
29. mwo.owl
30. namo.owl.ttl
31. nando_2025-08-26.ttl
32. oae_merged.owl
33. oba.owl
34. obi.owl
35. odfa.owl
36. ordo_orphanet.owl
37. pato.owl
38. pcl.owl
39. phases.owl
40. phipo.owl
41. plantso.owl
42. psdo.rdf
43. rbo.owl
44. sio-release.owl
45. sleep.rdf
46. slso.owl
47. ssbd_v20250512.ttl
48. tara-acupoints-inferred.rdf
49. uberon.owl
50. xpo.owl
✅ Ergebnisse gespeichert in Bio_Portal_ontology_functional_properties_full.csv
✅ Auswertung gespeichert: Bio_Portal_ontology_functional_properties_summary.csv

,Construct,Summe,#Ontologien,%Ontologien,Ø pro Ontologie (ohne 0),Ø pro Ontologie (mit 0),Median (ohne 0),Median (mit 0),Min (>0),Max,Werte (für Median ohne 0)
5,properties_total,7846,46,92.0,170.57,156.92,126.0,92.5,2,751,"[2, 2, 3, 4, 5, 9, 12, 14, 14, 21, 21, 31, 34,..."
0,object_properties_total,6556,46,92.0,142.52,131.12,86.5,66.0,2,679,"[2, 2, 3, 3, 4, 7, 9, 12, 12, 13, 14, 21, 21, ..."
1,datatype_properties_total,1290,30,60.0,43.00,25.80,5.5,1.0,1,438,"[1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 3, 4, 4, 4, 5, ..."
4,functional_total,127,24,48.0,5.29,2.54,3.0,0.0,1,27,"[1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, ..."
2,object_functional,93,23,46.0,4.04,1.86,3.0,0.0,1,18,"[1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3, ..."
3,datatype_functional,34,8,16.0,4.25,0.68,4.0,0.0,1,9,"[1, 1, 1, 4, 4, 7, 7, 9]"

In [ ]:
# --- Pfade ---
ONT_DIR = r"C:\Users\ilove\OneDrive\Uni\Master - Philipps Uni\Master Thesis\Ontologien\Zum Testen von Verteilungen von Konzepten\Bio Portal"
OUT_CSV = "complex_class_parts_detailed.csv"
OUT_SUMMARY = "complex_class_parts_summary.csv"

EXTS = (".owl", ".ttl", ".rdf", ".jsonld", ".nt", ".n3")

def count_parts_for_predicate(g: Graph, predicate):
    """
    Liefert Counter: {anzahl_teile: anzahl_vorkommen} für ein bestimmtes Prädikat
    (z. B. rdfs:subClassOf oder owl:equivalentClass)
    """
    counter = Counter()

    for s, _, o in g.triples((None, predicate, None)):
        if isinstance(o, BNode):
            coll_head = g.value(o, OWL.intersectionOf) or g.value(o, OWL.unionOf)
            if coll_head:
                try:
                    n_parts = len(list(Collection(g, coll_head)))
                except Exception:
                    n_parts = 1
            elif (o, RDF.type, OWL.Restriction) in g:
                n_parts = 1
            else:
                n_parts = 1
            counter[n_parts] += 1
    return counter


def count_complex_parts_by_type(g: Graph):
    """Zählt die Anzahl Teile komplexer Klassen nach Typ (sub/equiv/disjoint)."""
    distributions = defaultdict(Counter)

    # 1️⃣ rdfs:subClassOf
    distributions["sub"] = count_parts_for_predicate(g, RDFS.subClassOf)

    # 2️⃣ owl:equivalentClass
    distributions["eq"] = count_parts_for_predicate(g, OWL.equivalentClass)

    # 3️⃣ owl:disjointWith
    distributions["dis"] = count_parts_for_predicate(g, OWL.disjointWith)

    # Alle Counts zusammenführen in eine flache Dict-Struktur
    row = {}
    total_complex = 0
    for label, dist in distributions.items():
        for n_parts, count in sorted(dist.items()):
            row[f"{label}_parts_{n_parts}"] = count
            total_complex += count

    row["complex_class_count"] = total_complex
    return row


# --- Hauptlogik ---
rows = []
idx = 1

for fname in sorted(os.listdir(ONT_DIR)):
    if not fname.lower().endswith(EXTS):
        continue
    path = os.path.join(ONT_DIR, fname)
    print(f"{idx}. {fname}")
    idx += 1

    try:
        g = Graph()
        g.parse(path)
        stats = count_complex_parts_by_type(g)
    except Exception as e:
        print(f"   ⚠️ Fehler beim Parsen: {e}")
        stats = {"complex_class_count": 0, "_error": str(e)}

    row = {"file": fname, **stats}
    rows.append(row)

# --- DataFrame ---
df = pd.DataFrame(rows).fillna(0)

# Numerische Spalten konvertieren
num_cols = [c for c in df.columns if c != "file"]
df[num_cols] = df[num_cols].astype(int)

# --- CSV speichern ---
df.to_csv(OUT_CSV, index=False)
print(f"✅ Ergebnisse gespeichert in {OUT_CSV}")

df.head(10)

df = pd.read_csv(OUT_CSV)
N = len(df)

# Alle Konstruktspalten für die Auswertung:
# (Alles außer Datei-Name, _error und SUMME; Property-Typen bleiben drin – werden aber nicht zusammengezählt,
#  hier machen wir eine per-Konstrukt-Auswertung, also dürfen sie erscheinen.)
construct_cols = [c for c in df.columns if c not in ("file", "_error", "SUMME")]

summary_rows = []
for col in construct_cols:
    vals = pd.to_numeric(df[col], errors="coerce").fillna(0).astype(int)
    total = int(vals.sum())
    ont_count = int((vals > 0).sum())
    percent = (ont_count / N * 100) if N else 0

    nonzero_vals = sorted(vals[vals > 0].tolist())
    if ont_count > 0:
        avg = float(vals[vals > 0].mean())
        med = float(vals[vals > 0].median())
        minv = min(nonzero_vals)
        avg_0 = float(vals[vals >= 0].mean())
        med_0 = float(vals[vals >= 0].median())
    else:
        avg = med = minv = avg_0 = med_0 = 0.0
        
    maxv = int(vals.max()) if len(vals) else 0

    summary_rows.append({
        "Construct": col,
        "Summe": total,
        "#Ontologien": ont_count,
        "%Ontologien": round(percent, 1),
        "Ø pro Ontologie (ohne 0)": round(avg, 2),
        "Ø pro Ontologie (mit 0)": round(avg_0, 2),
        "Median (ohne 0)": med,
        "Median (mit 0)": med_0,
        "Min (>0)": minv,
        "Max": maxv,
        "Werte (für Median ohne 0)": nonzero_vals,  # hier alle Werte explizit
        # "Werte (für Median mit 0)": sorted(vals.tolist())
    })

summary_df = pd.DataFrame(summary_rows).sort_values(by=["Summe", "#Ontologien"], ascending=False)
summary_df.to_csv(OUT_SUMMARY, index=False)

print(f"✅ Auswertung gespeichert: {OUT_SUMMARY}")
summary_df.head(10)

In [ ]:
# Zählt Intersection, Union und Complement
ONT_DIR = r"C:\Users\ilove\OneDrive\Uni\Master - Philipps Uni\Master Thesis\Ontologien\Zum Testen von Verteilungen von Konzepten\Bio Portal"
OUT_CSV = "complex_class_union_intersection_complement_full.csv"
OUT_SUMMARY = "complex_class_union_intersection_complement_summary.csv"
EXTS = (".owl", ".ttl", ".rdf", ".jsonld", ".nt", ".n3")

def count_union_intersection_complement(g: Graph):
    """
    Zählt, wie oft intersectionOf, unionOf oder complementOf
    in komplexen Klassendefinitionen verwendet werden.
    Wenn kein explizites Konstrukt angegeben ist, aber mehrere BNodes vorkommen,
    wird dies als intersection (Schnittmenge) gewertet.
    """
    results = {
        "sub_intersection": 0,
        "sub_union": 0,
        "sub_complement": 0,
        "eq_intersection": 0,
        "eq_union": 0,
        "eq_complement": 0,
        "dis_intersection": 0,
        "dis_union": 0,
        "dis_complement": 0,
    }

    def analyze_complex_object(obj):
        """Erkennt intersectionOf/unionOf/complementOf oder schätzt AND, wenn mehrere Teile vorhanden."""
        if g.value(obj, OWL.intersectionOf):
            return "intersection"
        elif g.value(obj, OWL.unionOf):
            return "union"
        elif g.value(obj, OWL.complementOf):
            return "complement"
        else:
            # Kein expliziter Operator – prüfen, ob mehrere Restriktionen oder anonyme Teile vorhanden
            parts = []
            if (obj, RDF.type, OWL.Restriction) in g:
                parts.append(obj)
            for _, _, o2 in g.triples((obj, None, None)):
                if isinstance(o2, BNode) and (o2, RDF.type, OWL.Restriction) in g:
                    parts.append(o2)
            if len(parts) > 1:
                return "intersection"
            return None

    # --- subClassOf ---
    for _, _, o in g.triples((None, RDFS.subClassOf, None)):
        if isinstance(o, BNode):
            t = analyze_complex_object(o)
            if t:
                results[f"sub_{t}"] += 1

    # --- equivalentClass ---
    for _, _, o in g.triples((None, OWL.equivalentClass, None)):
        if isinstance(o, BNode):
            t = analyze_complex_object(o)
            if t:
                results[f"eq_{t}"] += 1

    # --- disjointWith ---
    for _, _, o in g.triples((None, OWL.disjointWith, None)):
        if isinstance(o, BNode):
            t = analyze_complex_object(o)
            if t:
                results[f"dis_{t}"] += 1

    # --- Gesamtsummen ---
    results["total_intersection"] = (
        results["sub_intersection"] + results["eq_intersection"] + results["dis_intersection"]
    )
    results["total_union"] = (
        results["sub_union"] + results["eq_union"] + results["dis_union"]
    )
    results["total_complement"] = (
        results["sub_complement"] + results["eq_complement"] + results["dis_complement"]
    )

    return results


# --- Hauptlogik ---
rows = []
idx = 1
for fname in sorted(os.listdir(ONT_DIR)):
    if not fname.lower().endswith((".owl", ".ttl", ".rdf", ".jsonld", ".nt", ".n3")):
        continue
    path = os.path.join(ONT_DIR, fname)
    print(f"{idx}. {fname}")
    idx += 1
    try:
        g = Graph()
        g.parse(path)
        stats = count_union_intersection_complement(g)
    except Exception as e:
        print(f"   ⚠️ Fehler beim Parsen: {e}")
        stats = {k: 0 for k in [
            "sub_intersection", "sub_union", "sub_complement",
            "eq_intersection", "eq_union", "eq_complement",
            "dis_intersection", "dis_union", "dis_complement",
            "total_intersection", "total_union", "total_complement"
        ]}
        stats["_error"] = str(e)

    row = {"file": fname, **stats}
    rows.append(row)

# --- DataFrame ---
df = pd.DataFrame(rows).fillna(0)
num_cols = [c for c in df.columns if c != "file"]
df[num_cols] = df[num_cols].astype(int)

# --- CSV speichern ---
df.to_csv(OUT_CSV, index=False)
print(f"✅ Ergebnisse gespeichert in {OUT_CSV}")

df.head(10)


df = pd.read_csv(OUT_CSV)
N = len(df)

# Alle Konstruktspalten für die Auswertung:
# (Alles außer Datei-Name, _error und SUMME; Property-Typen bleiben drin – werden aber nicht zusammengezählt,
#  hier machen wir eine per-Konstrukt-Auswertung, also dürfen sie erscheinen.)
construct_cols = [c for c in df.columns if c not in ("file", "_error", "SUMME")]

summary_rows = []
for col in construct_cols:
    vals = pd.to_numeric(df[col], errors="coerce").fillna(0).astype(int)
    total = int(vals.sum())
    ont_count = int((vals > 0).sum())
    percent = (ont_count / N * 100) if N else 0

    nonzero_vals = sorted(vals[vals > 0].tolist())
    if ont_count > 0:
        avg = float(vals[vals > 0].mean())
        med = float(vals[vals > 0].median())
        minv = min(nonzero_vals)
        avg_0 = float(vals[vals >= 0].mean())
        med_0 = float(vals[vals >= 0].median())
    else:
        avg = med = minv = avg_0 = med_0 = 0.0
        
    maxv = int(vals.max()) if len(vals) else 0

    summary_rows.append({
        "Construct": col,
        "Summe": total,
        "#Ontologien": ont_count,
        "%Ontologien": round(percent, 1),
        "Ø pro Ontologie (ohne 0)": round(avg, 2),
        "Ø pro Ontologie (mit 0)": round(avg_0, 2),
        "Median (ohne 0)": med,
        "Median (mit 0)": med_0,
        "Min (>0)": minv,
        "Max": maxv,
        "Werte (für Median ohne 0)": nonzero_vals,  # hier alle Werte explizit
        # "Werte (für Median mit 0)": sorted(vals.tolist())
    })

summary_df = pd.DataFrame(summary_rows).sort_values(by=["Summe", "#Ontologien"], ascending=False)
summary_df.to_csv(OUT_SUMMARY, index=False)

print(f"✅ Auswertung gespeichert: {OUT_SUMMARY}")
summary_df.head(10)

1. Allergidoc.rdf
2. BMONT.owl
3. CDMOnto.owl
4. COPPER.owl
5. CTCAE_5.0.owl
6. DMDSONT.rdf
7. EDAM.owl
8. GAMUTS.owl
9. O3_20250709.owl
10. OBOREL.owl
11. OntoCaimerV2-Joe-Mary.owl
12. bbo.rdf
13. bcio.owl
14. bervo.owl
15. cl.owl
16. clo_merged.owl
17. cob.owl
18. envo.owl
19. evora_ontology.ttl
20. foodon.owl
21. fypo.owl
22. gbol-ontology.ttl
23. hhear_properties.rdf
24. hso.owl
25. jfo_v005.ttl
26. meo.v.1.0.ttl
27. metpo.owl
28. mro.owl
29. mwo.owl
30. namo.owl.ttl
31. nando_2025-08-26.ttl
32. oae_merged.owl
33. oba.owl
34. obi.owl
35. odfa.owl
36. ordo_orphanet.owl
37. pato.owl
38. pcl.owl
39. phases.owl
40. phipo.owl
41. plantso.owl
42. psdo.rdf
43. rbo.owl
44. sio-release.owl
45. sleep.rdf
46. slso.owl
47. ssbd_v20250512.ttl
48. tara-acupoints-inferred.rdf
49. uberon.owl
50. xpo.owl
✅ Ergebnisse gespeichert in complex_class_union_intersection_complement_full.csv
✅ Auswertung gespeichert: complex_class_union_intersection_complement_summary.csv

,Construct,Summe,#Ontologien,%Ontologien,Ø pro Ontologie (ohne 0),Ø pro Ontologie (mit 0),Median (ohne 0),Median (mit 0),Min (>0),Max,Werte (für Median ohne 0)
9,total_intersection,164355,30,60.0,5478.50,3287.10,403.5,23.0,2.0,52118,"[2, 3, 12, 13, 18, 28, 37, 47, 55, 79, 98, 136..."
3,eq_intersection,147255,28,56.0,5259.11,2945.10,392.5,11.0,2.0,52101,"[2, 2, 10, 12, 13, 17, 29, 30, 41, 78, 110, 25..."
0,sub_intersection,17099,24,48.0,712.46,341.98,26.0,0.0,1.0,13775,"[1, 1, 1, 3, 7, 8, 11, 17, 17, 18, 21, 26, 26,..."
2,sub_complement,1172,10,20.0,117.20,23.44,39.0,0.0,2.0,377,"[2, 5, 5, 8, 18, 60, 69, 312, 316, 377]"
11,total_complement,1172,10,20.0,117.20,23.44,39.0,0.0,2.0,377,"[2, 5, 5, 8, 18, 60, 69, 312, 316, 377]"
10,total_union,601,28,56.0,21.46,12.02,14.5,1.0,1.0,145,"[1, 1, 1, 1, 1, 1, 2, 3, 4, 5, 5, 5, 8, 14, 15..."
4,eq_union,541,24,48.0,22.54,10.82,12.0,0.0,1.0,144,"[1, 1, 2, 3, 3, 5, 5, 5, 8, 10, 12, 12, 12, 13..."
1,sub_union,57,15,30.0,3.80,1.14,4.0,0.0,1.0,10,"[1, 1, 1, 1, 1, 1, 3, 4, 4, 4, 5, 5, 6, 10, 10]"
7,dis_union,3,1,2.0,3.00,0.06,3.0,0.0,3.0,3,[3]
6,dis_intersection,1,1,2.0,1.00,0.02,1.0,0.0,1.0,1,[1]

In [ ]:
# AllDisjointClasses 
ONT_DIR = r"C:\Users\ilove\OneDrive\Uni\Master - Philipps Uni\Master Thesis\Ontologien\Zum Testen von Verteilungen von Konzepten\Bio Portal"
OUT_CSV = "all_disjoint_classes_distribution.csv"
OUT_SUMMARY = "all_disjoint_classes_distribution_summary.csv"
EXTS = (".owl", ".ttl", ".rdf", ".jsonld", ".nt", ".n3")

def count_all_disjoint_distribution(g: Graph):
    """
    Zählt, wie viele owl:AllDisjointClasses-Axiome es gibt,
    die 2, 3, 4, ... Klassen enthalten.
    """
    size_counts = Counter()

    for axiom in g.subjects(RDF.type, OWL.AllDisjointClasses):
        members_head = g.value(axiom, OWL.members)
        if not members_head:
            continue
        try:
            members = list(Collection(g, members_head))
            size = len(members)
            if size >= 2:  # nur disjunkte Gruppen mit min. 2 Klassen
                size_counts[size] += 1
        except Exception:
            continue

    # Counter in reguläres Dict umwandeln (Spaltennamen: disjoint_<n>)
    return {f"disjoint_{n}": c for n, c in sorted(size_counts.items())}


# --- Hauptlogik ---
rows = []
idx = 1

for fname in sorted(os.listdir(ONT_DIR)):
    if not fname.lower().endswith(EXTS):
        continue

    path = os.path.join(ONT_DIR, fname)
    print(f"{idx}. {fname}")
    idx += 1

    try:
        g = Graph()
        g.parse(path)
        stats = count_all_disjoint_distribution(g)
    except Exception as e:
        print(f"   ⚠️ Fehler beim Parsen: {e}")
        stats = {}

    rows.append({"file": fname, **stats})

# --- DataFrame ---
df = pd.DataFrame(rows).fillna(0)
num_cols = [c for c in df.columns if c != "file"]
df[num_cols] = df[num_cols].astype(int)

# --- CSV speichern ---
df.to_csv(OUT_CSV, index=False)
print(f"✅ Ergebnisse gespeichert in {OUT_CSV}")

df.head(10)

df = pd.read_csv(OUT_CSV)
N = len(df)

# Alle Konstruktspalten für die Auswertung:
# (Alles außer Datei-Name, _error und SUMME; Property-Typen bleiben drin – werden aber nicht zusammengezählt,
#  hier machen wir eine per-Konstrukt-Auswertung, also dürfen sie erscheinen.)
construct_cols = [c for c in df.columns if c not in ("file", "_error", "SUMME")]

summary_rows = []
for col in construct_cols:
    vals = pd.to_numeric(df[col], errors="coerce").fillna(0).astype(int)
    total = int(vals.sum())
    ont_count = int((vals > 0).sum())
    percent = (ont_count / N * 100) if N else 0

    nonzero_vals = sorted(vals[vals > 0].tolist())
    if ont_count > 0:
        avg = float(vals[vals > 0].mean())
        med = float(vals[vals > 0].median())
        minv = min(nonzero_vals)
        avg_0 = float(vals[vals >= 0].mean())
        med_0 = float(vals[vals >= 0].median())
    else:
        avg = med = minv = avg_0 = med_0 = 0.0
        
    maxv = int(vals.max()) if len(vals) else 0

    summary_rows.append({
        "Construct": col,
        "Summe": total,
        "#Ontologien": ont_count,
        "%Ontologien": round(percent, 1),
        "Ø pro Ontologie (ohne 0)": round(avg, 2),
        "Ø pro Ontologie (mit 0)": round(avg_0, 2),
        "Median (ohne 0)": med,
        "Median (mit 0)": med_0,
        "Min (>0)": minv,
        "Max": maxv,
        "Werte (für Median ohne 0)": nonzero_vals,  # hier alle Werte explizit
        # "Werte (für Median mit 0)": sorted(vals.tolist())
    })

summary_df = pd.DataFrame(summary_rows).sort_values(by=["Summe", "#Ontologien"], ascending=False)
summary_df.to_csv(OUT_SUMMARY, index=False)

print(f"✅ Auswertung gespeichert: {OUT_SUMMARY}")
summary_df.head(10)

✅ Auswertung gespeichert: all_disjoint_classes_distribution_summary.csv

,Construct,Summe,#Ontologien,%Ontologien,Ø pro Ontologie (ohne 0),Ø pro Ontologie (mit 0),Median (ohne 0),Median (mit 0),Min (>0),Max,Werte (für Median ohne 0)
2,disjoint_3,49,15,30.0,3.27,0.98,3.0,0.0,1,8,"[1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 6, 8, 8]"
0,disjoint_4,30,16,32.0,1.88,0.60,1.5,0.0,1,5,"[1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 4, 5]"
6,disjoint_6,5,3,6.0,1.67,0.10,2.0,0.0,1,2,"[1, 2, 2]"
3,disjoint_7,4,4,8.0,1.00,0.08,1.0,0.0,1,1,"[1, 1, 1, 1]"
5,disjoint_5,4,2,4.0,2.00,0.08,2.0,0.0,2,2,"[2, 2]"
7,disjoint_8,2,2,4.0,1.00,0.04,1.0,0.0,1,1,"[1, 1]"
1,disjoint_28,1,1,2.0,1.00,0.02,1.0,0.0,1,1,[1]
4,disjoint_21,1,1,2.0,1.00,0.02,1.0,0.0,1,1,[1]
8,disjoint_13,1,1,2.0,1.00,0.02,1.0,0.0,1,1,[1]
9,disjoint_14,1,1,2.0,1.00,0.02,1.0,0.0,1,1,[1]

In [ ]:
# --- Pfade ---
ONT_DIR = r"C:\Users\ilove\OneDrive\Uni\Master - Philipps Uni\Master Thesis\Ontologien\Zum Testen von Verteilungen von Konzepten\Bio Portal"
OUT_CSV = "ontology_basic_entity_counts.csv"
EXTS = (".owl", ".ttl", ".rdf", ".jsonld", ".nt", ".n3")

def count_basic_entities(g: Graph):
    """
    Zählt Klassen, Properties (ohne Annotation Properties) und Individuen in einer Ontologie.
    """
    classes = set(g.subjects(RDF.type, OWL.Class))
    obj_props = set(g.subjects(RDF.type, OWL.ObjectProperty))
    data_props = set(g.subjects(RDF.type, OWL.DatatypeProperty))
    anno_props = set(g.subjects(RDF.type, OWL.AnnotationProperty))

    # Individuen: alle Subjekte, die kein Klassen- oder Property-Objekt sind
    all_subjects = {s for s, _, _ in g}
    technical = classes | obj_props | data_props | anno_props
    individuals = {s for s in all_subjects if s not in technical and isinstance(s, (str, type(next(iter(all_subjects), None))))}

    # Zählen
    return {
        "classes": len(classes),
        "object_properties": len(obj_props),
        "datatype_properties": len(data_props),
        "total_properties": len(obj_props | data_props),  # Annotation Props explizit ausgeschlossen
        "individuals": len(individuals),
    }


# --- Hauptlogik ---
rows = []
idx = 1
for fname in sorted(os.listdir(ONT_DIR)):
    if not fname.lower().endswith(EXTS):
        continue

    path = os.path.join(ONT_DIR, fname)
    print(f"{idx}. {fname}")
    idx += 1

    try:
        g = Graph()
        g.parse(path)
        stats = count_basic_entities(g)
    except Exception as e:
        print(f"   ⚠️ Fehler beim Parsen: {e}")
        stats = {"classes": 0, "object_properties": 0, "datatype_properties": 0, "total_properties": 0, "individuals": 0}

    rows.append({"file": fname, **stats})

# --- DataFrame ---
df = pd.DataFrame(rows)
df.to_csv(OUT_CSV, index=False)

print(f"✅ Ergebnisse gespeichert in {OUT_CSV}")
df.head(10)

1. Allergidoc.rdf
2. BMONT.owl
3. CDMOnto.owl
4. COPPER.owl
5. CTCAE_5.0.owl
6. DMDSONT.rdf
7. EDAM.owl
8. GAMUTS.owl
9. O3_20250709.owl
10. OBOREL.owl
11. OntoCaimerV2-Joe-Mary.owl
12. bbo.rdf
13. bcio.owl
14. bervo.owl
15. cl.owl
16. clo_merged.owl
17. cob.owl
18. envo.owl
19. evora_ontology.ttl
20. foodon.owl
21. fypo.owl
22. gbol-ontology.ttl
23. hhear_properties.rdf
24. hso.owl
25. jfo_v005.ttl
26. meo.v.1.0.ttl
27. metpo.owl
28. mro.owl
29. mwo.owl
30. namo.owl.ttl
31. nando_2025-08-26.ttl
32. oae_merged.owl
33. oba.owl
34. obi.owl
35. odfa.owl
36. ordo_orphanet.owl
37. pato.owl
38. pcl.owl
39. phases.owl
40. phipo.owl
41. plantso.owl
42. psdo.rdf
43. rbo.owl
44. sio-release.owl
45. sleep.rdf
46. slso.owl
47. ssbd_v20250512.ttl
48. tara-acupoints-inferred.rdf
49. uberon.owl
50. xpo.owl
✅ Ergebnisse gespeichert in ontology_basic_entity_counts.csv

,file,classes,object_properties,datatype_properties,total_properties,individuals
0,Allergidoc.rdf,1138,3,0,3,34
1,BMONT.owl,632,9,0,9,375
2,CDMOnto.owl,302,14,20,34,97
3,COPPER.owl,363,66,8,74,776
4,CTCAE_5.0.owl,4049,0,0,0,16066
5,DMDSONT.rdf,8,7,48,55,993
6,EDAM.owl,3513,12,0,12,635
7,GAMUTS.owl,16876,2,0,2,109181
8,O3_20250709.owl,538,2,0,2,14
9,OBOREL.owl,89,679,1,680,1126

In [3]:
# Tiefe von Komplexen Klassen
ONT_DIR = r"C:\Users\ilove\OneDrive\Uni\Master - Philipps Uni\Master Thesis\Ontologien\Zum Testen von Verteilungen von Konzepten\Bio Portal"
OUT_CSV = "Bio_Portal_ontology_complex_class_depth_full.csv"
OUT_SUMMARY = "Bio_Portal_ontology_complex_class_depth_summary.csv"
EXTS = (".owl", ".ttl", ".rdf", ".jsonld", ".nt", ".n3")

def class_expression_depth(g, node):
    """
    Rekursiv: Berechnet die maximale Tiefe einer Class Expression.
    """
    # Benannte Klasse → Tiefe 0
    if not isinstance(node, BNode):
        return 0

    max_child_depth = 0

    # --- Restriction ---
    if (node, RDF.type, OWL.Restriction) in g:
        for p in [OWL.someValuesFrom, OWL.allValuesFrom,
                  OWL.hasValue, OWL.onClass]:
            for _, _, o in g.triples((node, p, None)):
                max_child_depth = max(
                    max_child_depth,
                    class_expression_depth(g, o)
                )
        return 1 + max_child_depth

    # --- Boolean Class Constructors ---
    for op in [OWL.intersectionOf, OWL.unionOf, OWL.complementOf]:
        coll = g.value(node, op)
        if coll:
            depths = [
                class_expression_depth(g, item)
                for item in Collection(g, coll)
            ]
            return 1 + max(depths, default=0)

    # Fallback: anonymer Knoten
    return 1


rows = []


for fname in sorted(os.listdir(ONT_DIR)):

    if not fname.lower().endswith(EXTS):
        continue
    depths = []
    
    path = os.path.join(ONT_DIR, fname)
    a = Graph()
    a.parse(path)

    # subClassOf
    for _, _, o in a.triples((None, RDFS.subClassOf, None)):
        if isinstance(o, BNode):
            depths.append(class_expression_depth(a, o))

    # equivalentClass
    for _, _, o in a.triples((None, OWL.equivalentClass, None)):
        if isinstance(o, BNode):
            depths.append(class_expression_depth(a, o))

    # disjointWith
    for _, _, o in a.triples((None, OWL.disjointWith, None)):
        if isinstance(o, BNode):
            depths.append(class_expression_depth(a, o))
        
    # --- Verteilung ---
    depth_counter = Counter(depths)

    row = {"file": fname}

    for d, cnt in sorted(depth_counter.items()):
        row[f"depth_{d}"] = cnt

    if depths:
        row["max_depth"] = max(depths)
        row["avg_depth"] = round(sum(depths) / len(depths), 2)
        row["count_expressions"] = len(depths)
    else:
        row["max_depth"] = 0
        row["avg_depth"] = 0
        row["count_expressions"] = 0

    rows.append(row)

df = pd.DataFrame(rows)
df.to_csv(OUT_CSV, index=False)
print(f"✅ gespeichert: {OUT_CSV}")
df.head(10)

df = pd.read_csv(OUT_CSV)
N = len(df)

# Alle Konstruktspalten für die Auswertung:
# (Alles außer Datei-Name, _error und SUMME; Property-Typen bleiben drin – werden aber nicht zusammengezählt,
#  hier machen wir eine per-Konstrukt-Auswertung, also dürfen sie erscheinen.)
construct_cols = [c for c in df.columns if c not in ("file", "_error", "SUMME")]

summary_rows = []
for col in construct_cols:
    vals = pd.to_numeric(df[col], errors="coerce").fillna(0).astype(int)
    total = int(vals.sum())
    ont_count = int((vals > 0).sum())
    percent = (ont_count / N * 100) if N else 0

    nonzero_vals = sorted(vals[vals > 0].tolist())
    if ont_count > 0:
        avg = float(vals[vals > 0].mean())
        med = float(vals[vals > 0].median())
        minv = min(nonzero_vals)
        avg_0 = float(vals[vals >= 0].mean())
        med_0 = float(vals[vals >= 0].median())
    else:
        avg = med = minv = avg_0 = med_0 = 0.0
        
    maxv = int(vals.max()) if len(vals) else 0

    summary_rows.append({
        "Construct": col,
        "Summe": total,
        "#Ontologien": ont_count,
        "%Ontologien": round(percent, 1),
        "Ø pro Ontologie (ohne 0)": round(avg, 2),
        "Ø pro Ontologie (mit 0)": round(avg_0, 2),
        "Median (ohne 0)": med,
        "Median (mit 0)": med_0,
        "Min (>0)": minv,
        "Max": maxv,
        "Werte (für Median ohne 0)": nonzero_vals,  # hier alle Werte explizit
        # "Werte (für Median mit 0)": sorted(vals.tolist())
    })

summary_df = pd.DataFrame(summary_rows).sort_values(by=["Summe", "#Ontologien"], ascending=False)
summary_df.to_csv(OUT_SUMMARY, index=False)

print(f"✅ Auswertung gespeichert: {OUT_SUMMARY}")
summary_df.head(10)

✅ gespeichert: Bio_Portal_ontology_complex_class_depth_full.csv
✅ Auswertung gespeichert: Bio_Portal_ontology_complex_class_depth_summary.csv

,Construct,Summe,#Ontologien,%Ontologien,Ø pro Ontologie (ohne 0),Ø pro Ontologie (mit 0),Median (ohne 0),Median (mit 0),Min (>0),Max,Werte (für Median ohne 0)
2,count_expressions,618814,42,84.0,14733.67,12376.28,847.0,586.5,12,137200,"[12, 13, 19, 23, 70, 72, 76, 106, 155, 157, 17..."
3,depth_1,364661,42,84.0,8682.40,7293.22,586.5,333.0,12,109177,"[12, 13, 16, 22, 48, 54, 59, 66, 98, 118, 142,..."
4,depth_2,153284,31,62.0,4944.65,3065.68,336.0,21.5,1,41215,"[1, 1, 3, 9, 10, 17, 26, 36, 54, 59, 67, 140, ..."
6,depth_3,63315,27,54.0,2345.00,1266.30,20.0,1.0,1,25494,"[1, 1, 1, 1, 1, 3, 4, 5, 5, 6, 10, 16, 17, 20,..."
7,depth_5,26329,14,28.0,1880.64,526.58,24.0,0.0,1,16904,"[1, 1, 2, 2, 7, 8, 24, 24, 37, 498, 1356, 2613..."
5,depth_4,10712,23,46.0,465.74,214.24,5.0,0.0,1,8228,"[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 5, 5, 6, 8, ..."
11,depth_7,336,6,12.0,56.00,6.72,3.0,0.0,1,320,"[1, 1, 2, 4, 8, 320]"
0,max_depth,166,42,84.0,3.95,3.32,4.0,3.0,1,9,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, ..."
8,depth_6,166,12,24.0,13.83,3.32,2.0,0.0,1,89,"[1, 1, 1, 1, 1, 2, 2, 2, 6, 9, 51, 89]"
1,avg_depth,48,42,84.0,1.14,0.96,1.0,1.0,1,3,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."